// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.Partition;

public class Property
{
    [JsonPropertyName("sensitive")]
    public bool? Sensitive { get; set; }

    [JsonPropertyName("value")]
    public object? Value { get; set; }

}
