// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.CrsConversion.Models
{
    /// <summary>
    /// scaleConvergence
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScaleConvergence : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>convergence</summary>
        public double? Convergence { get; set; }
        /// <summary>Point representation for CRS operations</summary>
        public double? Point { get; set; }
        /// <summary>Scalefactor</summary>
        public double? Scalefactor { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.CrsConversion.Models.ScaleConvergence"/> and sets the default values.
        /// </summary>
        public ScaleConvergence()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.CrsConversion.Models.ScaleConvergence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.CrsConversion.Models.ScaleConvergence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.CrsConversion.Models.ScaleConvergence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "convergence", n => { Convergence = n.GetDoubleValue(); } },
                { "point", n => { Point = n.GetDoubleValue(); } },
                { "scalefactor", n => { Scalefactor = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("convergence", Convergence);
            writer.WriteDoubleValue("point", Point);
            writer.WriteDoubleValue("scalefactor", Scalefactor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
