// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.Register.Models
{
    /// <summary>
    /// Represents a model for TestActionRequest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TestActionRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Represents a model to create Action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Register.Models.CreateActionDto? Action { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Register.Models.CreateActionDto Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>testPayload</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Register.Models.JsonNode? TestPayload { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Register.Models.JsonNode TestPayload { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Register.Models.TestActionRequest"/> and sets the default values.
        /// </summary>
        public TestActionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Register.Models.TestActionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.Register.Models.TestActionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.Register.Models.TestActionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetObjectValue<global::OsduCsharpClient.Register.Models.CreateActionDto>(global::OsduCsharpClient.Register.Models.CreateActionDto.CreateFromDiscriminatorValue); } },
                { "testPayload", n => { TestPayload = n.GetObjectValue<global::OsduCsharpClient.Register.Models.JsonNode>(global::OsduCsharpClient.Register.Models.JsonNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::OsduCsharpClient.Register.Models.CreateActionDto>("action", Action);
            writer.WriteObjectValue<global::OsduCsharpClient.Register.Models.JsonNode>("testPayload", TestPayload);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
