// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.Legal.Models
{
    /// <summary>
    /// Represents the Search Query objects for Legaltags.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryLegalTag : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The limit property</summary>
        public int? Limit { get; set; }
        /// <summary>If there are multiple conditions need to be joined in by logical operators</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OperatorList { get; set; }
#nullable restore
#else
        public List<string> OperatorList { get; set; }
#endif
        /// <summary>Filter condition query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? QueryList { get; set; }
#nullable restore
#else
        public List<string> QueryList { get; set; }
#endif
        /// <summary>The sortBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortBy { get; set; }
#nullable restore
#else
        public string SortBy { get; set; }
#endif
        /// <summary>The sortOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortOrder { get; set; }
#nullable restore
#else
        public string SortOrder { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Legal.Models.QueryLegalTag"/> and sets the default values.
        /// </summary>
        public QueryLegalTag()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Legal.Models.QueryLegalTag"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.Legal.Models.QueryLegalTag CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.Legal.Models.QueryLegalTag();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "operatorList", n => { OperatorList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "queryList", n => { QueryList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sortBy", n => { SortBy = n.GetStringValue(); } },
                { "sortOrder", n => { SortOrder = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("limit", Limit);
            writer.WriteCollectionOfPrimitiveValues<string>("operatorList", OperatorList);
            writer.WriteCollectionOfPrimitiveValues<string>("queryList", QueryList);
            writer.WriteStringValue("sortBy", SortBy);
            writer.WriteStringValue("sortOrder", SortOrder);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
