// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\conversion\abcd\{namespaces}\{fromSymbol}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFromSymbolItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OsduCsharpClient.Unit.v2.conversion.abcd.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.Item.WithToSymbolItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.Item.WithToSymbolItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("toSymbol", position);
                return new global::OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.Item.WithToSymbolItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.WithFromSymbolItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFromSymbolItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/conversion/abcd/{namespaces}/{fromSymbol}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Abcd.Item.Item.WithFromSymbolItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFromSymbolItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/conversion/abcd/{namespaces}/{fromSymbol}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
