// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.Unit;

public class ABCD
{
    [JsonPropertyName("a")]
    public double? A { get; set; }

    [JsonPropertyName("c")]
    public double? C { get; set; }

    [JsonPropertyName("b")]
    public double? B { get; set; }

    [JsonPropertyName("d")]
    public double? D { get; set; }

}
