// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Osdu.Client.Apis.Unit;

public interface IUnitApiClient
{
    /// <summary>
    /// getUnitBySystemAndMeasurement
    /// </summary>
    Task<UnitSystem> GetV3UnitsystemAsync(string name, int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// postUnitSystem
    /// </summary>
    Task<UnitSystem> PostV3UnitsystemAsync(UnitSystemRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnits
    /// </summary>
    Task<QueryResult> GetV3UnitAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// postUnit
    /// </summary>
    Task<Unit> PostV3UnitAsync(UnitRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitBySystemAndMeasurement
    /// </summary>
    Task<Unit> GetV3UnitUnitsystemAsync(string unitSystemName, string ancestry, CancellationToken cancellationToken = default);

    /// <summary>
    /// postUnitBySystemAndMeasurement
    /// </summary>
    Task<Unit> PostV3UnitUnitsystemAsync(string unitSystemName, MeasurementRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// postSearchUnits
    /// </summary>
    Task<QueryResult> PostV3UnitSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// postUnitsByMeasurement
    /// </summary>
    Task<QueryResult> GetV3UnitMeasurementAsync(string ancestry, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitsByMeasurement
    /// </summary>
    Task<QueryResult> PostV3UnitMeasurementAsync(MeasurementRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// postPreferredUnitsByMeasurement
    /// </summary>
    Task<QueryResult> GetV3UnitMeasurementPreferredAsync(string ancestry, CancellationToken cancellationToken = default);

    /// <summary>
    /// postPreferredUnitsByMeasurement
    /// </summary>
    Task<QueryResult> PostV3UnitMeasurementPreferredAsync(MeasurementRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// getMeasurements
    /// </summary>
    Task<Measurement> GetV3MeasurementAsync(string ancestry, CancellationToken cancellationToken = default);

    /// <summary>
    /// postMeasurement
    /// </summary>
    Task<Measurement> PostV3MeasurementAsync(MeasurementRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// postSearchMeasurements
    /// </summary>
    Task<QueryResult> PostV3MeasurementSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getConversionScaleOffsetBySymbols
    /// </summary>
    Task<ConversionResult> GetV3ConversionScaleAsync(string namespaces, string fromSymbol, string toSymbol, CancellationToken cancellationToken = default);

    /// <summary>
    /// postConversionScaleOffset
    /// </summary>
    Task<ConversionResult> PostV3ConversionScaleAsync(ConversionScaleOffsetRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// postConversionABCD
    /// </summary>
    Task<ConversionResult> GetV3ConversionAbcdAsync(string namespaces, string fromSymbol, string toSymbol, CancellationToken cancellationToken = default);

    /// <summary>
    /// postConversionABCD
    /// </summary>
    Task<ConversionResult> PostV3ConversionAbcdAsync(ConversionABCDRequest body, CancellationToken cancellationToken = default);

    /// <summary>
    /// postSearch
    /// </summary>
    Task<QueryResult> PostV3CatalogSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitSystemInfoList
    /// </summary>
    Task<UnitSystemInfoResponse> GetV3UnitsystemListAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitsBySymbol
    /// </summary>
    Task<QueryResult> GetV3UnitSymbolsAsync(string symbol, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitBySymbol
    /// </summary>
    Task<Unit> GetV3UnitSymbolAsync(string namespaces, string symbol, CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitMaps
    /// </summary>
    Task<QueryResult> GetV3UnitMapsAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getMeasurementMaps
    /// </summary>
    Task<QueryResult> GetV3MeasurementMapsAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getMeasurements
    /// </summary>
    Task<QueryResult> GetV3MeasurementListAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// info
    /// </summary>
    Task<VersionInfo> GetV3InfoAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// getCatalog
    /// </summary>
    Task<Catalog> GetV3CatalogAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// getUnitMaps
    /// </summary>
    Task<QueryResult> GetV3CatalogMapstatesAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// getLastModified
    /// </summary>
    Task<CatalogLastModified> GetV3CatalogLastmodifiedAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Readiness Check endpoint
    /// </summary>
    Task<string> GetV3AhReadinessCheckAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Liveness Check endpoint
    /// </summary>
    Task<string> GetV3AhLivenessCheckAsync(CancellationToken cancellationToken = default);

}

public partial class UnitApiClient : IUnitApiClient
{
    private readonly HttpClient _httpClient;
    private readonly JsonSerializerOptions _jsonOptions;
    private readonly string _baseUrl;

    public UnitApiClient(HttpClient httpClient)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        _baseUrl = "/api/unit";
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
    }

    /// <summary>
    /// getUnitBySystemAndMeasurement
    /// </summary>
    public async Task<UnitSystem> GetV3UnitsystemAsync(string name, int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"name={Uri.EscapeDataString(name.ToString()!)}");
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unitsystem{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<UnitSystem>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postUnitSystem
    /// </summary>
    public async Task<UnitSystem> PostV3UnitsystemAsync(UnitSystemRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unitsystem{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<UnitSystem>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnits
    /// </summary>
    public async Task<QueryResult> GetV3UnitAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postUnit
    /// </summary>
    public async Task<Unit> PostV3UnitAsync(UnitRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/unit";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Unit>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitBySystemAndMeasurement
    /// </summary>
    public async Task<Unit> GetV3UnitUnitsystemAsync(string unitSystemName, string ancestry, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"unitSystemName={Uri.EscapeDataString(unitSystemName.ToString()!)}");
        queryParts.Add($"ancestry={Uri.EscapeDataString(ancestry.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/unitsystem{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Unit>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postUnitBySystemAndMeasurement
    /// </summary>
    public async Task<Unit> PostV3UnitUnitsystemAsync(string unitSystemName, MeasurementRequest body, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"unitSystemName={Uri.EscapeDataString(unitSystemName.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/unitsystem{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Unit>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postSearchUnits
    /// </summary>
    public async Task<QueryResult> PostV3UnitSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/search{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postUnitsByMeasurement
    /// </summary>
    public async Task<QueryResult> GetV3UnitMeasurementAsync(string ancestry, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"ancestry={Uri.EscapeDataString(ancestry.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/measurement{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitsByMeasurement
    /// </summary>
    public async Task<QueryResult> PostV3UnitMeasurementAsync(MeasurementRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/unit/measurement";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postPreferredUnitsByMeasurement
    /// </summary>
    public async Task<QueryResult> GetV3UnitMeasurementPreferredAsync(string ancestry, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"ancestry={Uri.EscapeDataString(ancestry.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/measurement/preferred{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postPreferredUnitsByMeasurement
    /// </summary>
    public async Task<QueryResult> PostV3UnitMeasurementPreferredAsync(MeasurementRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/unit/measurement/preferred";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getMeasurements
    /// </summary>
    public async Task<Measurement> GetV3MeasurementAsync(string ancestry, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"ancestry={Uri.EscapeDataString(ancestry.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/measurement{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Measurement>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postMeasurement
    /// </summary>
    public async Task<Measurement> PostV3MeasurementAsync(MeasurementRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/measurement";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Measurement>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postSearchMeasurements
    /// </summary>
    public async Task<QueryResult> PostV3MeasurementSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/measurement/search{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getConversionScaleOffsetBySymbols
    /// </summary>
    public async Task<ConversionResult> GetV3ConversionScaleAsync(string namespaces, string fromSymbol, string toSymbol, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"namespaces={Uri.EscapeDataString(namespaces.ToString()!)}");
        queryParts.Add($"fromSymbol={Uri.EscapeDataString(fromSymbol.ToString()!)}");
        queryParts.Add($"toSymbol={Uri.EscapeDataString(toSymbol.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/conversion/scale{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<ConversionResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postConversionScaleOffset
    /// </summary>
    public async Task<ConversionResult> PostV3ConversionScaleAsync(ConversionScaleOffsetRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/conversion/scale";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<ConversionResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postConversionABCD
    /// </summary>
    public async Task<ConversionResult> GetV3ConversionAbcdAsync(string namespaces, string fromSymbol, string toSymbol, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"namespaces={Uri.EscapeDataString(namespaces.ToString()!)}");
        queryParts.Add($"fromSymbol={Uri.EscapeDataString(fromSymbol.ToString()!)}");
        queryParts.Add($"toSymbol={Uri.EscapeDataString(toSymbol.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/conversion/abcd{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<ConversionResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postConversionABCD
    /// </summary>
    public async Task<ConversionResult> PostV3ConversionAbcdAsync(ConversionABCDRequest body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/conversion/abcd";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<ConversionResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// postSearch
    /// </summary>
    public async Task<QueryResult> PostV3CatalogSearchAsync(SearchRequest body, int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/catalog/search{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitSystemInfoList
    /// </summary>
    public async Task<UnitSystemInfoResponse> GetV3UnitsystemListAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unitsystem/list{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<UnitSystemInfoResponse>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitsBySymbol
    /// </summary>
    public async Task<QueryResult> GetV3UnitSymbolsAsync(string symbol, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"symbol={Uri.EscapeDataString(symbol.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/symbols{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitBySymbol
    /// </summary>
    public async Task<Unit> GetV3UnitSymbolAsync(string namespaces, string symbol, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        queryParts.Add($"namespaces={Uri.EscapeDataString(namespaces.ToString()!)}");
        queryParts.Add($"symbol={Uri.EscapeDataString(symbol.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/symbol{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Unit>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitMaps
    /// </summary>
    public async Task<QueryResult> GetV3UnitMapsAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/unit/maps{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getMeasurementMaps
    /// </summary>
    public async Task<QueryResult> GetV3MeasurementMapsAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/measurement/maps{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getMeasurements
    /// </summary>
    public async Task<QueryResult> GetV3MeasurementListAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/measurement/list{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// info
    /// </summary>
    public async Task<VersionInfo> GetV3InfoAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/info";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<VersionInfo>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getCatalog
    /// </summary>
    public async Task<Catalog> GetV3CatalogAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/catalog";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<Catalog>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getUnitMaps
    /// </summary>
    public async Task<QueryResult> GetV3CatalogMapstatesAsync(int? offset = default, int? limit = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (offset is not null)
            queryParts.Add($"offset={Uri.EscapeDataString(offset.ToString()!)}");
        if (limit is not null)
            queryParts.Add($"limit={Uri.EscapeDataString(limit.ToString()!)}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/v3/catalog/mapstates{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<QueryResult>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// getLastModified
    /// </summary>
    public async Task<CatalogLastModified> GetV3CatalogLastmodifiedAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/catalog/lastmodified";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<CatalogLastModified>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Readiness Check endpoint
    /// </summary>
    public async Task<string> GetV3AhReadinessCheckAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/_ah/readiness_check";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

    /// <summary>
    /// Liveness Check endpoint
    /// </summary>
    public async Task<string> GetV3AhLivenessCheckAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/v3/_ah/liveness_check";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

}
