// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Unit;

/// <summary>
/// Request to get a single unit instance given an essence.
/// </summary>
public class UnitRequest
{
    /// <summary>
    /// The persistable reference string for the unit; optional, only one 'persistableReference' or 'essence' must be defined
    /// </summary>
    [JsonPropertyName("persistableReference")]
    public string PersistableReference { get; set; }

    /// <summary>
    /// The essence of a unit parameterization
    /// </summary>
    [JsonPropertyName("essence")]
    public UnitEssenceImpl? Essence { get; set; }

}
