// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OsduCsharpClient.IngestionWorkflowService.Models;
using OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workflow\{workflow_name}\workflowRun
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowRunRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OsduCsharpClient.IngestionWorkflowService.v1.workflow.item.workflowRun.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.Item.WithRunItemRequestBuilder"/></returns>
        public global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.Item.WithRunItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("runId", position);
                return new global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.Item.WithRunItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowRunRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflow/{workflow_name}/workflowRun?params={params}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowRunRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflow/{workflow_name}/workflowRun?params={params}", rawUrl)
        {
        }
        /// <summary>
        /// Get all run instances for a worflow. **Required roles** - &apos;service.workflow.viewer&apos;.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRun"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 404 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 409 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 500 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 502 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRun?> GetAsync(Action<RequestConfiguration<global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder.WorkflowRunRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRun> GetAsync(Action<RequestConfiguration<global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder.WorkflowRunRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "409", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "500", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "502", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "503", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRun>(requestInfo, global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRun.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Trigger a workflow mentioned in payload. **Required roles** - &apos;service.workflow.creator&apos;.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRunResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 404 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 409 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 500 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 502 status code</exception>
        /// <exception cref="global::OsduCsharpClient.IngestionWorkflowService.Models.AppError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRunResponse?> PostAsync(global::OsduCsharpClient.IngestionWorkflowService.Models.TriggerWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRunResponse> PostAsync(global::OsduCsharpClient.IngestionWorkflowService.Models.TriggerWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "409", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "500", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "502", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
                { "503", global::OsduCsharpClient.IngestionWorkflowService.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRunResponse>(requestInfo, global::OsduCsharpClient.IngestionWorkflowService.Models.WorkflowRunResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all run instances for a worflow. **Required roles** - &apos;service.workflow.viewer&apos;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder.WorkflowRunRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder.WorkflowRunRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Trigger a workflow mentioned in payload. **Required roles** - &apos;service.workflow.creator&apos;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.IngestionWorkflowService.Models.TriggerWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.IngestionWorkflowService.Models.TriggerWorkflowRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/v1/workflow/{workflow_name}/workflowRun", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OsduCsharpClient.IngestionWorkflowService.V1.Workflow.Item.WorkflowRun.WorkflowRunRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all run instances for a worflow. **Required roles** - &apos;service.workflow.viewer&apos;.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkflowRunRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("params")]
            public string? Params { get; set; }
#nullable restore
#else
            [QueryParameter("params")]
            public string Params { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
