// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.Search;

/// <summary>
/// Intersection filter returning results whose geometry intersects the given polygons.
/// </summary>
public class ByIntersection
{
    /// <summary>
    /// List of polygons each defined by a set of points.
    /// </summary>
    [Required]
    [JsonPropertyName("polygons")]
    public List<Polygon> Polygons { get; set; }

}
