// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Search;

/// <summary>
/// Within-polygon filter returning results contained within the given polygon.
/// </summary>
public class ByWithinPolygon
{
    /// <summary>
    /// Polygon defined by a set of points.
    /// </summary>
    [Required]
    [JsonPropertyName("points")]
    public List<Point> Points { get; set; }

}
