// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.Policy;

public class UserDetailRequestModel
{
    [Required]
    [JsonPropertyName("user_detail")]
    public UserDetailsModel UserDetail { get; set; }

    [JsonPropertyName("ttl")]
    public UserDetailRequestModelTtl? Ttl { get; set; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(UserDetailRequestModelTtlVariant1), "UserDetailRequestModelTtlVariant1")]
[JsonDerivedType(typeof(UserDetailRequestModelTtlVariant2), "UserDetailRequestModelTtlVariant2")]
public abstract class UserDetailRequestModelTtl
{
}

public class UserDetailRequestModelTtlVariant1 : UserDetailRequestModelTtl
{
}

public class UserDetailRequestModelTtlVariant2 : UserDetailRequestModelTtl
{
}
