// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OsduCsharpClient.Unit.Models;
using OsduCsharpClient.Unit.V2.Conversion.Scale.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OsduCsharpClient.Unit.V2.Conversion.Scale
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\conversion\scale
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScaleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OsduCsharpClient.Unit.v2.conversion.scale.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Scale.Item.WithNamespacesItemRequestBuilder"/></returns>
        public global::OsduCsharpClient.Unit.V2.Conversion.Scale.Item.WithNamespacesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("namespaces", position);
                return new global::OsduCsharpClient.Unit.V2.Conversion.Scale.Item.WithNamespacesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Scale.ScaleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScaleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/conversion/scale", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Scale.ScaleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScaleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/conversion/scale", rawUrl)
        {
        }
        /// <summary>
        /// Get the scale/offset unit parameters given the &apos;fromUnit&apos; and &apos;toUnit&apos;. The &apos;fromUnit&apos; and &apos;toUnit&apos; definitions can either be passed as persistable reference strings (JSON serialized Unit essence) or as Unit essence structures.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Unit.Models.ConversionResult"/></returns>
        /// <param name="body">A scale offset unit conversion request. The requested units are either passed as persistable reference strings (JSON serialized Unit &apos;essence&apos;) or as Unit essence structure.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 404 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 409 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 500 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 502 status code</exception>
        /// <exception cref="global::OsduCsharpClient.Unit.Models.AppError">When receiving a 503 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OsduCsharpClient.Unit.Models.ConversionResult?> PostAsync(global::OsduCsharpClient.Unit.Models.ConversionScaleOffsetRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OsduCsharpClient.Unit.Models.ConversionResult> PostAsync(global::OsduCsharpClient.Unit.Models.ConversionScaleOffsetRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "409", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "500", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "502", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
                { "503", global::OsduCsharpClient.Unit.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OsduCsharpClient.Unit.Models.ConversionResult>(requestInfo, global::OsduCsharpClient.Unit.Models.ConversionResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the scale/offset unit parameters given the &apos;fromUnit&apos; and &apos;toUnit&apos;. The &apos;fromUnit&apos; and &apos;toUnit&apos; definitions can either be passed as persistable reference strings (JSON serialized Unit essence) or as Unit essence structures.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A scale offset unit conversion request. The requested units are either passed as persistable reference strings (JSON serialized Unit &apos;essence&apos;) or as Unit essence structure.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.Unit.Models.ConversionScaleOffsetRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.Unit.Models.ConversionScaleOffsetRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Unit.V2.Conversion.Scale.ScaleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::OsduCsharpClient.Unit.V2.Conversion.Scale.ScaleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OsduCsharpClient.Unit.V2.Conversion.Scale.ScaleRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
