// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.WellboreDdms;

public class Catalog
{
    [Required]
    [JsonPropertyName("family_catalog")]
    public List<CatalogItem> FamilyCatalog { get; set; }

    [JsonPropertyName("main_family_catalog")]
    public CatalogMainFamilyCatalog? MainFamilyCatalog { get; set; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(CatalogMainFamilyCatalogVariant1), "CatalogMainFamilyCatalogVariant1")]
[JsonDerivedType(typeof(CatalogMainFamilyCatalogVariant2), "CatalogMainFamilyCatalogVariant2")]
public abstract class CatalogMainFamilyCatalog
{
}

public class CatalogMainFamilyCatalogVariant1 : CatalogMainFamilyCatalog
{
}

public class CatalogMainFamilyCatalogVariant2 : CatalogMainFamilyCatalog
{
}
