// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.WellboreDdms;

public class CreateUpdateRecordsResponse
{
    [JsonPropertyName("recordCount")]
    public long? RecordCount { get; set; }

    [JsonPropertyName("recordIdVersions")]
    public List<string>? RecordIdVersions { get; set; }

    [JsonPropertyName("recordIds")]
    public List<string>? RecordIds { get; set; }

    [JsonPropertyName("skippedRecordIds")]
    public List<string>? SkippedRecordIds { get; set; }

}
