// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.WellboreDdms;

public class GuessResponse
{
    [JsonPropertyName("family")]
    public string? Family { get; set; }

    [JsonPropertyName("family_type")]
    public List<string>? FamilyType { get; set; }

    [JsonPropertyName("log_unit")]
    public string? LogUnit { get; set; }

    [JsonPropertyName("base_unit")]
    public string? BaseUnit { get; set; }

}
