// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.WellboreDdms;

public class MainFamilyCatalogItem
{
    [Required]
    [JsonPropertyName("MainFamily")]
    public string MainFamily { get; set; }

    [Required]
    [JsonPropertyName("Family")]
    public string Family { get; set; }

    [Required]
    [JsonPropertyName("Unit")]
    public string Unit { get; set; }

}
