// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.CrsCatalog;

/// <summary>
/// BaseCRS
/// </summary>
public class BaseCRS
{
    /// <summary>
    /// Record Id of parent CRS
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// Name of parent CRS
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; }

}
