// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Storage;

public class RecordHeadersDTO
{
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// Access control lists defining which groups can view or own a record.
    /// </summary>
    [JsonPropertyName("acl")]
    public Acl? Acl { get; set; }

    [JsonPropertyName("legal")]
    public Legal? Legal { get; set; }

    /// <summary>
    /// Ancestry information for a record, listing the parent record references from which this record was derived.
    /// </summary>
    [JsonPropertyName("ancestry")]
    public RecordAncestry? Ancestry { get; set; }

    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    [JsonPropertyName("createTime")]
    public string CreateTime { get; set; }

    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("modifyTime")]
    public string ModifyTime { get; set; }

}
