// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// This abstract entity gathers all the properties universally required to describe any kind of reservoir - at multiple levels of granularity (e.g. Reservoir or Reservoir Segment).
/// </summary>
public class AbstractGenericReservoirUnit_2_0_0
{
    /// <summary>
    /// Name of the reservoir or reservoir segment.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The productive area is the measured or estimated total area of the reservoir unit considered, usually the area within the hydrocarbon-water contact.
    /// </summary>
    [JsonPropertyName("ReservoirUnitArea")]
    public double? ReservoirUnitArea { get; set; }

    /// <summary>
    /// This flag indicates that this reservoir is composed of reservoir segments, and that the characteristics of the segments should be aggregated to best describe the characteristics of the reservoir. When not segmented, the single reservoir segment describes the properties of the entire reservoir. If more than one reservoir segment is defined for this reservoir, this flag should be set and the characteristics for the reservoir should be calculated as summary data over all its reservoir segments.
    /// </summary>
    [JsonPropertyName("IsSegmented")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsSegmented { get; set; }

    /// <summary>
    /// The date that commercial production first began in the Reservoir or Reservoir Segment.
    /// </summary>
    [JsonPropertyName("FirstProductionDate")]
    public DateOnly FirstProductionDate { get; set; }

    /// <summary>
    /// The date that CO2 storage injection first began in the Reservoir or Reservoir Segment.
    /// </summary>
    [JsonPropertyName("FirstCO2StorageInjectionDate")]
    public DateOnly FirstCO2StorageInjectionDate { get; set; }

    /// <summary>
    /// Indicates the current life cycle status of the reservoir in a simple way for the ease of searching. This same status may also be found in the LifeCycleStatuses array, providing the actual status dates.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ReservoirLifeCycleStatus:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CurrentLifeCycleStatusID")]
    public string CurrentLifeCycleStatusID { get; set; }

    /// <summary>
    /// Indicates whether the condition of a Reservoir or Reservoir Segment is Active, meaning there is at least one well intentionally and currently interacting with the reservoir or reservoir segment. The absence of a value should not be assumed to mean true (Active) or false (Inactive).
    /// </summary>
    [JsonPropertyName("IsActiveCondition")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsActiveCondition { get; set; }

    /// <summary>
    /// This is the best estimate of the original hydrocarbon total pore volume of the reservoir segment at initial conditions.
    /// </summary>
    [JsonPropertyName("OriginalHydrocarbonPoreVolume")]
    public double? OriginalHydrocarbonPoreVolume { get; set; }

    /// <summary>
    /// An array of remarks that provide more context for this data record.
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

    /// <summary>
    /// The average true vertical depth from the Vertical CRS to the top of the reservoir unit. This is further qualified by the associated Vertical CRS property. If no Vertical CRS is populated, assume Mean Sea Level, and therefore "TVD Subsea".
    /// </summary>
    [JsonPropertyName("ReservoirUnitTopDepthTVD")]
    public double? ReservoirUnitTopDepthTVD { get; set; }

    /// <summary>
    /// The true vertical depth from the Vertical CRS to the permanent reservoir unit datum used for pressure. This is further qualified by the associated Vertical CRS property. If no Vertical CRS is populated, assume Mean Sea Level, and therefore "TVD Subsea".
    /// </summary>
    [JsonPropertyName("ReservoirUnitPressureDatumTVD")]
    public double? ReservoirUnitPressureDatumTVD { get; set; }

    /// <summary>
    /// The Vertical Coordinate Reference System defining the origin (i.e., zero point) for the vertical measurements on this data record (e.g. PressureDatum and TopDepth). The most common Vertical CRS in this context is Mean Sea Level. Populating this attribute is especially important when the Vertical CRS is not Mean Sea Level but rather a local alternative like Caspian height or a custom Vertical CRS.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalCRSID")]
    public string VerticalCRSID { get; set; }

    /// <summary>
    /// If the the vertical measurements on this data record (e.g. PressureDatum and TopDepth) were not referenced from Mean Sea Level, this attribute can capture the difference between the selected Vertical CRS and Mean Sea Level.
    /// </summary>
    [JsonPropertyName("VerticalDatumOffsetToMeanSeaLevel")]
    public double? VerticalDatumOffsetToMeanSeaLevel { get; set; }

    /// <summary>
    /// Set of attributes capturing the Life Cycle Statuses of the Reservoir, a concept which is typically chronological.
    /// </summary>
    [JsonPropertyName("LifeCycleStatuses")]
    public List<AbstractGenericReservoirUnit_2_0_0_LifeCycleStatuses> LifeCycleStatuses { get; set; }

}

/// <summary>
/// Set of attributes capturing the Life Cycle Statuses of the Reservoir, a concept which is typically chronological.
/// </summary>
public class AbstractGenericReservoirUnit_2_0_0_LifeCycleStatuses
{
    /// <summary>
    /// The Life Cycle Status of the Reservoir, a concept which is typically chronological.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ReservoirLifeCycleStatus:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("LifeCycleStatusID")]
    public string LifeCycleStatusID { get; set; }

    /// <summary>
    /// Date of a status change
    /// </summary>
    [JsonPropertyName("StatusDate")]
    public DateOnly StatusDate { get; set; }

    /// <summary>
    /// The date and time at which the reservoir status type becomes effective.
    /// </summary>
    [JsonPropertyName("EffectiveDateTime")]
    public DateOnly EffectiveDateTime { get; set; }

    /// <summary>
    /// The date and time at which the reservoir status type is no longer in effect.
    /// </summary>
    [JsonPropertyName("TerminationDateTime")]
    public DateOnly TerminationDateTime { get; set; }

}
