// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// A simple uncertainty quantification for a point location.
/// </summary>
public class AbstractLocationUncertainty_1_0_0
{
    /// <summary>
    /// Position uncertainty refers to the radius around a given location that is likely to contain the true value of the measurement with a specified confidence level. The position is defined in three-dimensional space with x, y, and z coordinates. For instance, if the location uncertainty radius is 1.5 meters and the confidence level is 1 sigma (approximately 61% using Rayleigh distribution), it means that the actual location is expected to be within a sphere of 1.5 meters radius from the reported position 61% of the time.
    /// </summary>
    [JsonPropertyName("Radius3D")]
    public double? Radius3D { get; set; }

    /// <summary>
    /// The confidence level, expressed as sigma and using Rayleigh distribution, indicates the degree of certainty that the predicted three-dimensional location is accurate. For example, if the location uncertainty radius is 1.5 meters and the confidence level is 1 sigma, it means that the actual position is expected to fall within a sphere with a radius of 1.5 meters from the reported position 61% of the time. The radius represents the extent of this sphere, defined by the location uncertainty. For a three-dimensional position given in x, y, and z coordinates, the rule of thumb for sigma levels is as follows when using Rayleigh distribution: 1 sigma corresponds to a 61% confidence level, 2 sigma corresponds to a 99% confidence level and 3 sigma corresponds to nearly a 100% confidence level. In comparison, for a one-dimensional case assuming Gaussian distribution, these sigma levels represent: 1 sigma corresponds to a 68% confidence level, 2 sigma corresponds to a 95% confidence level and 3 sigma corresponds to a 99.7% confidence level.
    /// </summary>
    [JsonPropertyName("ConfidenceLevel")]
    public double? ConfidenceLevel { get; set; }

}
