// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// A Project is a business activity that consumes financial and human resources and produces (digital) work products.
/// </summary>
public class AbstractProject_1_0_0
{
    /// <summary>
    /// Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the "Source" property should identify that source system.
    /// </summary>
    [JsonPropertyName("ProjectID")]
    public string ProjectID { get; set; }

    /// <summary>
    /// The common or preferred name of a Project.
    /// </summary>
    [JsonPropertyName("ProjectName")]
    public string ProjectName { get; set; }

    /// <summary>
    /// DEPRECATED: please use data.NameAliases. The history of Project names, codes, and other business identifiers.
    /// </summary>
    [JsonPropertyName("ProjectNames")]
    public List<AbstractAliasNames_1_0_0> ProjectNames { get; set; }

    /// <summary>
    /// Description of the objectives of a Project.
    /// </summary>
    [JsonPropertyName("Purpose")]
    public string Purpose { get; set; }

    /// <summary>
    /// The date and time when the Project was initiated.
    /// </summary>
    [JsonPropertyName("ProjectBeginDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ProjectBeginDate { get; set; }

    /// <summary>
    /// The date and time when the Project was completed.
    /// </summary>
    [JsonPropertyName("ProjectEndDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ProjectEndDate { get; set; }

    /// <summary>
    /// The history of expenditure approvals.
    /// </summary>
    [JsonPropertyName("FundsAuthorizations")]
    public List<AbstractProject_1_0_0_FundsAuthorizations> FundsAuthorizations { get; set; }

    /// <summary>
    /// References to applicable agreements in external contract database system of record.
    /// </summary>
    [JsonPropertyName("ContractIDs")]
    public List<string> ContractIDs { get; set; }

    /// <summary>
    /// The organisation which controlled the conduct of the project.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("Operator")]
    public string Operator { get; set; }

    /// <summary>
    /// References to organisations which supplied services to the Project.
    /// </summary>
    [JsonPropertyName("Contractors")]
    public List<AbstractProject_1_0_0_Contractors> Contractors { get; set; }

    /// <summary>
    /// List of key individuals supporting the Project.  This could be Abstracted for re-use, and could reference a separate Persons master data object.
    /// </summary>
    [JsonPropertyName("Personnel")]
    public List<AbstractProject_1_0_0_Personnel> Personnel { get; set; }

    /// <summary>
    /// General parameters defining the configuration of the Project.  In the case of a seismic acquisition project it is like receiver interval, source depth, source type.  In the case of a processing project, it is like replacement velocity, reference datum above mean sea level.
    /// </summary>
    [JsonPropertyName("ProjectSpecifications")]
    public List<AbstractProject_1_0_0_ProjectSpecifications> ProjectSpecifications { get; set; }

    /// <summary>
    /// The history of life cycle states that the Project has been through..
    /// </summary>
    [JsonPropertyName("ProjectStates")]
    public List<AbstractProject_1_0_0_ProjectStates> ProjectStates { get; set; }

}

/// <summary>
/// The history of expenditure approvals.
/// </summary>
public class AbstractProject_1_0_0_FundsAuthorizations
{
    /// <summary>
    /// Internal Company control number which identifies the allocation of funds to the Project.
    /// </summary>
    [JsonPropertyName("AuthorizationID")]
    public string AuthorizationID { get; set; }

    /// <summary>
    /// The date and time when the funds were approved.
    /// </summary>
    [JsonPropertyName("EffectiveDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? EffectiveDateTime { get; set; }

    /// <summary>
    /// The level of expenditure approved.
    /// </summary>
    [JsonPropertyName("FundsAmount")]
    public double? FundsAmount { get; set; }

    /// <summary>
    /// Type of currency for the authorized expenditure.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-Currency:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CurrencyID")]
    public string CurrencyID { get; set; }

}

/// <summary>
/// References to organisations which supplied services to the Project.
/// </summary>
public class AbstractProject_1_0_0_Contractors
{
    /// <summary>
    /// Reference to a company that provided services.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ContractorOrganisationID")]
    public string ContractorOrganisationID { get; set; }

    /// <summary>
    /// Name of the team, unit, crew, party, or other subdivision of the Contractor that provided services.
    /// </summary>
    [JsonPropertyName("ContractorCrew")]
    public string ContractorCrew { get; set; }

    /// <summary>
    /// The identifier of a reference value for the role of a contractor providing services, such as Recording, Line Clearing, Positioning, Data Processing.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ContractorType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ContractorTypeID")]
    public string ContractorTypeID { get; set; }

}

/// <summary>
/// List of key individuals supporting the Project.  This could be Abstracted for re-use, and could reference a separate Persons master data object.
/// </summary>
public class AbstractProject_1_0_0_Personnel
{
    /// <summary>
    /// Name of an individual supporting the Project.
    /// </summary>
    [JsonPropertyName("PersonName")]
    public string PersonName { get; set; }

    /// <summary>
    /// Reference to the company which employs Personnel.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CompanyOrganisationID")]
    public string CompanyOrganisationID { get; set; }

    /// <summary>
    /// The identifier of a reference value for the role of an individual supporting a Project, such as Project Manager, Party Chief, Client Representative, Senior Observer.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ProjectRole:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProjectRoleID")]
    public string ProjectRoleID { get; set; }

}

/// <summary>
/// General parameters defining the configuration of the Project.  In the case of a seismic acquisition project it is like receiver interval, source depth, source type.  In the case of a processing project, it is like replacement velocity, reference datum above mean sea level.
/// </summary>
public class AbstractProject_1_0_0_ProjectSpecifications
{
    /// <summary>
    /// The date and time at which a ProjectSpecification becomes effective.
    /// </summary>
    [JsonPropertyName("EffectiveDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? EffectiveDateTime { get; set; }

    /// <summary>
    /// The date and time at which a ProjectSpecification is no longer in effect.
    /// </summary>
    [JsonPropertyName("TerminationDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? TerminationDateTime { get; set; }

    /// <summary>
    /// The value for the specified parameter type.
    /// </summary>
    [JsonPropertyName("ProjectSpecificationQuantity")]
    public double? ProjectSpecificationQuantity { get; set; }

    /// <summary>
    /// The actual date and time value of the parameter.  ISO format permits specification of time or date only.
    /// </summary>
    [JsonPropertyName("ProjectSpecificationDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ProjectSpecificationDateTime { get; set; }

    /// <summary>
    /// The actual indicator value of the parameter.
    /// </summary>
    [JsonPropertyName("ProjectSpecificationIndicator")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? ProjectSpecificationIndicator { get; set; }

    /// <summary>
    /// The actual text value of the parameter.
    /// </summary>
    [JsonPropertyName("ProjectSpecificationText")]
    public string ProjectSpecificationText { get; set; }

    /// <summary>
    /// The unit for the quantity parameter if overriding the default for this ParameterType, like metre (m in SI units system) for quantity Length.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("UnitOfMeasureID")]
    public string UnitOfMeasureID { get; set; }

    /// <summary>
    /// Parameter type of property or characteristic.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ParameterType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ParameterTypeID")]
    public string ParameterTypeID { get; set; }

}

/// <summary>
/// The history of life cycle states that the Project has been through..
/// </summary>
public class AbstractProject_1_0_0_ProjectStates
{
    /// <summary>
    /// The date and time at which the state becomes effective.
    /// </summary>
    [JsonPropertyName("EffectiveDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? EffectiveDateTime { get; set; }

    /// <summary>
    /// The date and time at which the state is no longer in effect.
    /// </summary>
    [JsonPropertyName("TerminationDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? TerminationDateTime { get; set; }

    /// <summary>
    /// The Project life cycle state from planning to completion.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ProjectStateType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProjectStateTypeID")]
    public string ProjectStateTypeID { get; set; }

}
