// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// A condition, which causes a re-evaluation of the decision and optionally the re-execution of a workflow.
/// </summary>
public class AbstractTrigger_1_0_0
{
    /// <summary>
    /// The condition expressed as human readable text, which triggers the re-evaluation of the decision.
    /// </summary>
    [JsonPropertyName("Condition")]
    public string Condition { get; set; }

    /// <summary>
    /// An array of free remarks or annotations.
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark100> Remarks { get; set; }

    /// <summary>
    /// Relationships to zero or more activity templates representing workflows, which need to be executed when the condition is met.
    /// </summary>
    [JsonPropertyName("WorkflowIDs")]
    public List<string> WorkflowIDs { get; set; }

}
