// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// The group of elements which all column grid layers (ijk or unstructured) contain
/// </summary>
public class AbstractColumnLayerGridPatch_1_0_0
{
    /// <summary>
    /// Count of cells in the K-direction (aka third and/or slowest and/or vertical direction) in the grid. Must be positive.
    /// </summary>
    [JsonPropertyName("Nk")]
    public int? Nk { get; set; }

    /// <summary>
    /// Indicate the K direction of the grid : up, down or not monotonic
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-KDirectionType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("KDirectionID")]
    public string KDirectionID { get; set; }

    /// <summary>
    /// Indicate if at least two adjacent nodes in K Direction are collocated. Also known as pinched node. Usually occur in erosional context.
    /// </summary>
    [JsonPropertyName("HasCollocatedNodeInKDirection")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasCollocatedNodeInKDirection { get; set; }

    /// <summary>
    /// Indicate the most complex pillar shape of a grid : vertical, straight, curved
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-PillarShapeType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PillarShapeID")]
    public string PillarShapeID { get; set; }

    /// <summary>
    /// Indicate that it exists at least one gap in the lateral direction of the grid. A gap is really a hole, it is not a slice of dead cells.
    /// </summary>
    [JsonPropertyName("HasLateralGaps")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasLateralGaps { get; set; }

    /// <summary>
    /// Indicate that it exists at least one gap in the whole K direction of the grid. A gap is really a hole, it is not a layer of dead cells.
    /// </summary>
    [JsonPropertyName("HasKGaps")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasKGaps { get; set; }

    /// <summary>
    /// Indicate that the nodes of the grid are given by means of a parameter along the pillar. Otherwise nodes of the grid are explicitly given by means of an XYZ triplet.
    /// </summary>
    [JsonPropertyName("HasParametricGeometry")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasParametricGeometry { get; set; }

    /// <summary>
    /// Indicate that the grid contains some split nodes i.e some node which are not on a pillar.
    /// </summary>
    [JsonPropertyName("HasSplitNode")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasSplitNode { get; set; }

    /// <summary>
    /// Indicate that some of the pillars of the grid are truncated (Fault contact in Y shape for example)
    /// </summary>
    [JsonPropertyName("HasTruncations")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? HasTruncations { get; set; }

    /// <summary>
    /// Indicate if a grid has been topologically expanded in a particular dimension (K expansion, J expansion, I expansion)
    /// </summary>
    [JsonPropertyName("ExpansionInDirection")]
    public AbstractColumnLayerGridPatch_1_0_0_ExpansionInDirection ExpansionInDirection { get; set; }

}

/// <summary>
/// Indicate if a grid has been topologically expanded in a particular dimension (K expansion, J expansion, I expansion)
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractColumnLayerGridPatch_1_0_0_ExpansionInDirection
{
    [JsonStringEnumMemberName("I")]
    I,

    [JsonStringEnumMemberName("J")]
    J,

    [JsonStringEnumMemberName("K")]
    K,

}
