// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Schemas.Abstract;

/// <summary>
/// The ColumnBasedTable is a set of columns, which have equal length (data.ColumnSize) included by types carrying embedded table properties. Columns have a Property Kind, UnitOfMeasure and Facet. There are KeyColumns (index columns) and Columns (for look-up values). Examples are KrPc, PVT and Facies tables.
/// </summary>
public class AbstractColumnBasedTable_1_0_0
{
    /// <summary>
    /// A column whose values are considered as keys/indices. Do not use this attribute if you want to follow a given ColumnBasedTableType.
    /// </summary>
    [JsonPropertyName("KeyColumns")]
    public List<AbstractReferencePropertyType_1_1_0> KeyColumns { get; set; }

    /// <summary>
    /// A common column storing values of a particular property kind. Do not use this attribute if you want to follow a given ColumnBasedTableType.
    /// </summary>
    [JsonPropertyName("Columns")]
    public List<AbstractReferencePropertyType_1_1_0> Columns { get; set; }

    /// <summary>
    /// The count of elements in each column
    /// </summary>
    [JsonPropertyName("ColumnSize")]
    public int? ColumnSize { get; set; }

    /// <summary>
    /// First column values are related to first key column, second column values are related to the second key column, etc…
    /// Column values at index KeyColumns count are related to first (non key) column, Column values at index KeyColumns count + 1 are related to second (non key) column, etc...
    /// </summary>
    [JsonPropertyName("ColumnValues")]
    public List<AbstractColumnBasedTable_1_0_0_ColumnValues> ColumnValues { get; set; }

    /// <summary>
    /// Quickly indicate the type of the column based table (KrPc, PVT, Facies, ...) and its standard columns definition. It is supposed to be used when you don't use KeyColumns neither Columns as attributes of this WPC.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ColumnBasedTableType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ColumnBasedTableType")]
    public string ColumnBasedTableType { get; set; }

}

/// <summary>
/// Value of the column. Generally only one of the attribute should be instantiated.
/// </summary>
public class AbstractColumnBasedTable_1_0_0_ColumnValues
{
    /// <summary>
    /// A column of only boolean values
    /// </summary>
    [JsonPropertyName("BooleanColumn")]
    public List<bool> BooleanColumn { get; set; }

    /// <summary>
    /// A column of only integer values
    /// </summary>
    [RegularExpression(@"^[0-9]+$")]
    [JsonPropertyName("IntegerColumn")]
    public List<int> IntegerColumn { get; set; }

    /// <summary>
    /// A column of only number values
    /// </summary>
    [JsonPropertyName("NumberColumn")]
    public List<double> NumberColumn { get; set; }

    /// <summary>
    /// A column of only string values
    /// </summary>
    [JsonPropertyName("StringColumn")]
    public List<string> StringColumn { get; set; }

    /// <summary>
    /// The row indexes for which the values are flagged as undefined.
    /// </summary>
    [RegularExpression(@"^[0-9]+$")]
    [JsonPropertyName("UndefinedValueRows")]
    public List<int> UndefinedValueRows { get; set; }

}
