// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OsduCsharpClient.CrsConversion.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OsduCsharpClient.CrsConversion.V2.ConvertTrajectory
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\convertTrajectory
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConvertTrajectoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.CrsConversion.V2.ConvertTrajectory.ConvertTrajectoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertTrajectoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/convertTrajectory", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.CrsConversion.V2.ConvertTrajectory.ConvertTrajectoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertTrajectoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/convertTrajectory", rawUrl)
        {
        }
        /// <summary>
        /// Convert a list of trajectory stations, given the unit and spatial context and a reference point in 3D where MD==0.  + Note: To get WGS 84 output the trajectoryCRS needs to be a BoundCRS (unless it is WGS 84 based)
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryResponse"/></returns>
        /// <param name="body">Input trajectory data structure; contains the context (crs, units, azimuth reference, method)</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryResponse?> PostAsync(global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryResponse> PostAsync(global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryResponse>(requestInfo, global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Convert a list of trajectory stations, given the unit and spatial context and a reference point in 3D where MD==0.  + Note: To get WGS 84 output the trajectoryCRS needs to be a BoundCRS (unless it is WGS 84 based)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Input trajectory data structure; contains the context (crs, units, azimuth reference, method)</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.CrsConversion.Models.ConvertTrajectoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.CrsConversion.V2.ConvertTrajectory.ConvertTrajectoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OsduCsharpClient.CrsConversion.V2.ConvertTrajectory.ConvertTrajectoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OsduCsharpClient.CrsConversion.V2.ConvertTrajectory.ConvertTrajectoryRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
