// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.Policy.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Input : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The datapartitionid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid? Datapartitionid { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid Datapartitionid { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Policy.Models.Input.Input_groups? Groups { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Policy.Models.Input.Input_groups Groups { get; set; }
#endif
        /// <summary>The operation property</summary>
        public global::OsduCsharpClient.Policy.Models.Input_operation? Operation { get; set; }
        /// <summary>The token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Policy.Models.Input.Input_token? Token { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Policy.Models.Input.Input_token Token { get; set; }
#endif
        /// <summary>The xuserid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OsduCsharpClient.Policy.Models.Input.Input_xuserid? Xuserid { get; set; }
#nullable restore
#else
        public global::OsduCsharpClient.Policy.Models.Input.Input_xuserid Xuserid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Policy.Models.Input"/> and sets the default values.
        /// </summary>
        public Input()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Policy.Models.Input"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.Policy.Models.Input CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.Policy.Models.Input();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datapartitionid", n => { Datapartitionid = n.GetObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid>(global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid.CreateFromDiscriminatorValue); } },
                { "groups", n => { Groups = n.GetObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_groups>(global::OsduCsharpClient.Policy.Models.Input.Input_groups.CreateFromDiscriminatorValue); } },
                { "operation", n => { Operation = n.GetEnumValue<global::OsduCsharpClient.Policy.Models.Input_operation>(); } },
                { "token", n => { Token = n.GetObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_token>(global::OsduCsharpClient.Policy.Models.Input.Input_token.CreateFromDiscriminatorValue); } },
                { "xuserid", n => { Xuserid = n.GetObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_xuserid>(global::OsduCsharpClient.Policy.Models.Input.Input_xuserid.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid>("datapartitionid", Datapartitionid);
            writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_groups>("groups", Groups);
            writer.WriteEnumValue<global::OsduCsharpClient.Policy.Models.Input_operation>("operation", Operation);
            writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_token>("token", Token);
            writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input.Input_xuserid>("xuserid", Xuserid);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Input_datapartitionid : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1? InputDatapartitionidMember1 { get; set; }
#nullable restore
#else
            public global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1 InputDatapartitionidMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::OsduCsharpClient.Policy.Models.Input.Input_datapartitionid();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.InputDatapartitionidMember1 = new global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InputDatapartitionidMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(InputDatapartitionidMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input_datapartitionidMember1>(null, InputDatapartitionidMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::OsduCsharpClient.Policy.Models.Input_groupsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Input_groups : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::OsduCsharpClient.Policy.Models.Input_groupsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::OsduCsharpClient.Policy.Models.Input_groupsMember1? InputGroupsMember1 { get; set; }
#nullable restore
#else
            public global::OsduCsharpClient.Policy.Models.Input_groupsMember1 InputGroupsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::OsduCsharpClient.Policy.Models.Input.Input_groups"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::OsduCsharpClient.Policy.Models.Input.Input_groups CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::OsduCsharpClient.Policy.Models.Input.Input_groups();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.InputGroupsMember1 = new global::OsduCsharpClient.Policy.Models.Input_groupsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InputGroupsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(InputGroupsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input_groupsMember1>(null, InputGroupsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::OsduCsharpClient.Policy.Models.Input_tokenMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Input_token : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::OsduCsharpClient.Policy.Models.Input_tokenMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::OsduCsharpClient.Policy.Models.Input_tokenMember1? InputTokenMember1 { get; set; }
#nullable restore
#else
            public global::OsduCsharpClient.Policy.Models.Input_tokenMember1 InputTokenMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::OsduCsharpClient.Policy.Models.Input.Input_token"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::OsduCsharpClient.Policy.Models.Input.Input_token CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::OsduCsharpClient.Policy.Models.Input.Input_token();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.InputTokenMember1 = new global::OsduCsharpClient.Policy.Models.Input_tokenMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InputTokenMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(InputTokenMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input_tokenMember1>(null, InputTokenMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::OsduCsharpClient.Policy.Models.Input_xuseridMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Input_xuserid : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::OsduCsharpClient.Policy.Models.Input_xuseridMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::OsduCsharpClient.Policy.Models.Input_xuseridMember1? InputXuseridMember1 { get; set; }
#nullable restore
#else
            public global::OsduCsharpClient.Policy.Models.Input_xuseridMember1 InputXuseridMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::OsduCsharpClient.Policy.Models.Input.Input_xuserid"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::OsduCsharpClient.Policy.Models.Input.Input_xuserid CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::OsduCsharpClient.Policy.Models.Input.Input_xuserid();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.InputXuseridMember1 = new global::OsduCsharpClient.Policy.Models.Input_xuseridMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InputXuseridMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(InputXuseridMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::OsduCsharpClient.Policy.Models.Input_xuseridMember1>(null, InputXuseridMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
