// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.Storage.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MultiRecordInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The invalidRecords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InvalidRecords { get; set; }
#nullable restore
#else
        public List<string> InvalidRecords { get; set; }
#endif
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Storage.Models.Record>? Records { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Storage.Models.Record> Records { get; set; }
#endif
        /// <summary>The retryRecords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RetryRecords { get; set; }
#nullable restore
#else
        public List<string> RetryRecords { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Storage.Models.MultiRecordInfo"/> and sets the default values.
        /// </summary>
        public MultiRecordInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Storage.Models.MultiRecordInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.Storage.Models.MultiRecordInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.Storage.Models.MultiRecordInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "invalidRecords", n => { InvalidRecords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Storage.Models.Record>(global::OsduCsharpClient.Storage.Models.Record.CreateFromDiscriminatorValue)?.AsList(); } },
                { "retryRecords", n => { RetryRecords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("invalidRecords", InvalidRecords);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Storage.Models.Record>("records", Records);
            writer.WriteCollectionOfPrimitiveValues<string>("retryRecords", RetryRecords);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
