// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.ReferenceData;

/// <summary>
/// Used to describe any kind of coordinate reference system. The type is identified by CoordinateReferenceSystemType (used by the system) and Kind facing the end-user. The Code is according to OSDU standard a string, the EPSG standard number is available via the CodeAsNumber property. Description carries EPSG's Remark. AttributionAuthority carries EPSG's DataSource. AliasNames carry the EPSG Alias contents.
/// </summary>
public class CoordinateReferenceSystem_1_1_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public CoordinateReferenceSystem_1_1_0_Data? Data { get; set; }

}

public class CoordinateReferenceSystem_1_1_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractReferenceType_1_0_0
{
    /// <summary>
    /// The name of the entity instance.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Alternative names, including historical, by which this entity instance is/has been known.
    /// </summary>
    [JsonPropertyName("NameAlias")]
    public List<AbstractAliasNames_1_0_0> NameAlias { get; set; }

    /// <summary>
    /// Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the "Source" property should identify that source system.
    /// </summary>
    [JsonPropertyName("ID")]
    public string ID { get; set; }

    /// <summary>
    /// By default reference values are considered as 'active'. An absent 'InactiveIndicator' property value means the reference value is in active use. When 'InactiveIndicator' is set true the reverence value is no longer in use and should no longer be offered as a choice.
    /// </summary>
    [JsonPropertyName("InactiveIndicator")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? InactiveIndicator { get; set; }

    /// <summary>
    /// The text which describes a NAME TYPE in detail.
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// The abbreviation or mnemonic for a reference type if defined. Example: WELL and WLBR.
    /// </summary>
    [JsonPropertyName("Code")]
    public string Code { get; set; }

    /// <summary>
    /// Name of the authority, or organisation, which governs the entity value and from which it is sourced.
    /// </summary>
    [JsonPropertyName("AttributionAuthority")]
    public string AttributionAuthority { get; set; }

    /// <summary>
    /// Name, URL, or other identifier of the publication, or repository, of the attribution source organisation from which the entity value is sourced.
    /// </summary>
    [JsonPropertyName("AttributionPublication")]
    public string AttributionPublication { get; set; }

    /// <summary>
    /// The distinct instance of the attribution publication, by version number, sequence number, date of publication, etc., that was used for the entity value.
    /// </summary>
    [JsonPropertyName("AttributionRevision")]
    public string AttributionRevision { get; set; }

    /// <summary>
    /// For reference values published and governed by OSDU: The date and time the record was committed into the OSDU member GitLab reference-values repository. The sole purpose of this date is to optimise the OSDU milestone upgrades. It allows the upgrade code to figure out whether or not the record must be PUT into reference value storage.
    /// </summary>
    [JsonPropertyName("CommitDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CommitDate { get; set; }

    /// <summary>
    /// The namespace or authority name governing this CRS definition, e.g. EPSG for contents from the EPSG Geodetic Parameter Dataset.
    /// </summary>
    [JsonPropertyName("CodeSpace")]
    public string CodeSpace { get; set; }

    /// <summary>
    /// The InformationSource providing the CRS definition if different from AttributionAuthority.
    /// </summary>
    [JsonPropertyName("InformationSource")]
    public string InformationSource { get; set; }

    /// <summary>
    /// The revision date of this CRS.
    /// </summary>
    [JsonPropertyName("RevisionDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? RevisionDate { get; set; }

    /// <summary>
    /// The kind of CRS, e.g. bound, compound, derived, engineering, geocentric, geographic 2D, geographic 3D, projected, vertical.
    /// </summary>
    [JsonPropertyName("Kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The code as number as opposed to the Code defined as a string.
    /// </summary>
    [JsonPropertyName("CodeAsNumber")]
    public int? CodeAsNumber { get; set; }

    /// <summary>
    /// The type of coordinate reference system. This is an enumeration of concrete sub-types.
    /// </summary>
    [JsonPropertyName("CoordinateReferenceSystemType")]
    public CoordinateReferenceSystem_1_1_0_Data_CoordinateReferenceSystemType CoordinateReferenceSystemType { get; set; }

    /// <summary>
    /// The horizontal CRS reference of a CompoundCRS. Only populated for CoordinateReferenceSystemType==CompoundCRS.
    /// </summary>
    [JsonPropertyName("HorizontalCRS")]
    public CoordinateReferenceSystem_1_1_0_Data_HorizontalCRS? HorizontalCRS { get; set; }

    /// <summary>
    /// The vertical CRS reference of a CompoundCRS. Only populated for CoordinateReferenceSystemType==CompoundCRS.
    /// </summary>
    [JsonPropertyName("VerticalCRS")]
    public CoordinateReferenceSystem_1_1_0_Data_VerticalCRS? VerticalCRS { get; set; }

    /// <summary>
    /// The Transformation bound to the BaseCRS in a BoundCRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
    /// </summary>
    [JsonPropertyName("Transformation")]
    public CoordinateReferenceSystem_1_1_0_Data_Transformation? Transformation { get; set; }

    /// <summary>
    /// The datum of this CRS. Only populated for CoordinateReferenceSystemType in [GeographicCRS, VerticalCRS, EngineeringCRS].
    /// </summary>
    [JsonPropertyName("Datum")]
    public CoordinateReferenceSystem_1_1_0_Data_Datum? Datum { get; set; }

    /// <summary>
    /// The DatumEnsemble for the CRS's datum. Only populated for GeographicCRS.
    /// </summary>
    [JsonPropertyName("DatumEnsemble")]
    public CoordinateReferenceSystem_1_1_0_Data_DatumEnsemble? DatumEnsemble { get; set; }

    /// <summary>
    /// The projection operation of a ProjectedCRS. Only populated for CoordinateReferenceSystemType==ProjectedCRS.
    /// </summary>
    [JsonPropertyName("Projection")]
    public CoordinateReferenceSystem_1_1_0_Data_Projection? Projection { get; set; }

    /// <summary>
    /// The base geographic CRS of this projected CRS. Only populated for CoordinateReferenceSystemType==ProjectedCRS.
    /// </summary>
    [JsonPropertyName("BaseCRS")]
    public CoordinateReferenceSystem_1_1_0_Data_BaseCRS? BaseCRS { get; set; }

    /// <summary>
    /// The source CRS of a BoundCRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
    /// </summary>
    [JsonPropertyName("SourceCRS")]
    public CoordinateReferenceSystem_1_1_0_Data_SourceCRS? SourceCRS { get; set; }

    /// <summary>
    /// The target CRS of this bound CRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
    /// </summary>
    [JsonPropertyName("TargetCRS")]
    public CoordinateReferenceSystem_1_1_0_Data_TargetCRS? TargetCRS { get; set; }

    /// <summary>
    /// Contextual information about scope and extent/area of use.
    /// </summary>
    [JsonPropertyName("Usages")]
    public List<CoordinateReferenceSystem_1_1_0_Data_Usages> Usages { get; set; }

    /// <summary>
    /// The coordinate system defining the dimension and individual axes used by the CRS.
    /// </summary>
    [JsonPropertyName("CoordinateSystem")]
    public CoordinateReferenceSystem_1_1_0_Data_CoordinateSystem? CoordinateSystem { get; set; }

    /// <summary>
    /// Scope and extent information about the described CRS.
    /// </summary>
    [JsonPropertyName("PreferredUsage")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage? PreferredUsage { get; set; }

    /// <summary>
    /// Used for export and actionable instructions to a conversion/transformation engine. It is initially based on Esri well-known text (WKT). Eventually, when Esri WKT are convertible into ISO WKT and vice versa, the definition can be replaced by https://proj.org/schemas/v0.2/projjson.schema.json.
    /// </summary>
    [JsonPropertyName("PersistableReference")]
    public string PersistableReference { get; set; }

    [JsonPropertyName("Wgs84Coordinates")]
    public AbstractFeatureCollection_1_0_0? Wgs84Coordinates { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// The type of coordinate reference system. This is an enumeration of concrete sub-types.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CoordinateReferenceSystem_1_1_0_Data_CoordinateReferenceSystemType
{
    [JsonStringEnumMemberName("BoundCRS")]
    BoundCRS,

    [JsonStringEnumMemberName("CompoundCRS")]
    CompoundCRS,

    [JsonStringEnumMemberName("DerivedCRS")]
    DerivedCRS,

    [JsonStringEnumMemberName("EngineeringCRS")]
    EngineeringCRS,

    [JsonStringEnumMemberName("GeodeticCRS")]
    GeodeticCRS,

    [JsonStringEnumMemberName("ProjectedCRS")]
    ProjectedCRS,

    [JsonStringEnumMemberName("VerticalCRS")]
    VerticalCRS,

}

/// <summary>
/// The horizontal CRS reference of a CompoundCRS. Only populated for CoordinateReferenceSystemType==CompoundCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_HorizontalCRS
{
    /// <summary>
    /// The HorizontalCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_HorizontalCRS_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the HorizontalCrs.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the HorizontalCrs.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("HorizontalCRSID")]
    public string HorizontalCRSID { get; set; }

}

/// <summary>
/// The HorizontalCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_HorizontalCRS_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The vertical CRS reference of a CompoundCRS. Only populated for CoordinateReferenceSystemType==CompoundCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_VerticalCRS
{
    /// <summary>
    /// The VerticalCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_VerticalCRS_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the VerticalCrs.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the VerticalCrs.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalCRSID")]
    public string VerticalCRSID { get; set; }

}

/// <summary>
/// The VerticalCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_VerticalCRS_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The Transformation bound to the BaseCRS in a BoundCRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Transformation
{
    /// <summary>
    /// The Transformation authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Transformation_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Transformation.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the bound transformation.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateTransformation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TransformationID")]
    public string TransformationID { get; set; }

}

/// <summary>
/// The Transformation authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Transformation_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The datum of this CRS. Only populated for CoordinateReferenceSystemType in [GeographicCRS, VerticalCRS, EngineeringCRS].
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Datum
{
    /// <summary>
    /// The Datum authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Datum_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Datum.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The Datum authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Datum_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The DatumEnsemble for the CRS's datum. Only populated for GeographicCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_DatumEnsemble
{
    /// <summary>
    /// The DatumEnsemble authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_DatumEnsemble_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the DatumEnsemble.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The DatumEnsemble authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_DatumEnsemble_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The projection operation of a ProjectedCRS. Only populated for CoordinateReferenceSystemType==ProjectedCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Projection
{
    /// <summary>
    /// The Projection Operation authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Projection_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the projection.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The Projection Operation authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Projection_AuthorityCode
{
    /// <summary>
    /// The projection operation  authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The projection operation code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The base geographic CRS of this projected CRS. Only populated for CoordinateReferenceSystemType==ProjectedCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_BaseCRS
{
    /// <summary>
    /// The BaseCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_BaseCRS_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the base CRS.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the BaseCRS.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("BaseCRSID")]
    public string BaseCRSID { get; set; }

}

/// <summary>
/// The BaseCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_BaseCRS_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The source CRS of a BoundCRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_SourceCRS
{
    /// <summary>
    /// The SourceCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_SourceCRS_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Source CRS.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the source CoordinateRefSystem.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SourceCRSID")]
    public string SourceCRSID { get; set; }

}

/// <summary>
/// The SourceCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_SourceCRS_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The target CRS of this bound CRS. Only populated for CoordinateReferenceSystemType==BoundCRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_TargetCRS
{
    /// <summary>
    /// The TargetCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_TargetCRS_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the base CRS.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The relationship to the TargetCRS.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TargetCRSID")]
    public string TargetCRSID { get; set; }

}

/// <summary>
/// The TargetCRS authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_TargetCRS_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Scope and extent information about the described CRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages
{
    /// <summary>
    /// The Usage authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Usages_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Usage.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Extent or area of use information.
    /// </summary>
    [JsonPropertyName("Extent")]
    public CoordinateReferenceSystem_1_1_0_Data_Usages_Extent? Extent { get; set; }

    /// <summary>
    /// Scope declaration.
    /// </summary>
    [JsonPropertyName("Scope")]
    public CoordinateReferenceSystem_1_1_0_Data_Usages_Scope? Scope { get; set; }

}

/// <summary>
/// The Usage authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Extent or area of use information.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages_Extent
{
    /// <summary>
    /// The Extent authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Usages_Extent_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Extent.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The description of the Extent.
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// Southern latitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxSouthBoundLatitude")]
    public double? BoundingBoxSouthBoundLatitude { get; set; }

    /// <summary>
    /// Western longitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxWestBoundLongitude")]
    public double? BoundingBoxWestBoundLongitude { get; set; }

    /// <summary>
    /// Eastern longitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxEastBoundLongitude")]
    public double? BoundingBoxEastBoundLongitude { get; set; }

    /// <summary>
    /// Northern latitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxNorthBoundLatitude")]
    public double? BoundingBoxNorthBoundLatitude { get; set; }

}

/// <summary>
/// The Extent authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages_Extent_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Scope declaration.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages_Scope
{
    /// <summary>
    /// The Scope authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_Usages_Scope_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Scope.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The Scope authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_Usages_Scope_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// The coordinate system defining the dimension and individual axes used by the CRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_CoordinateSystem
{
    /// <summary>
    /// The CoordinateSystem authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_CoordinateSystem_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Coordinate System.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The horizontal unit for 2-dimensional or 3-dimensional coordinate systems. This property is not populated for 1-dimensional coordinate systems (Vertical CRSs).
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("HorizontalAxisUnitID")]
    public string HorizontalAxisUnitID { get; set; }

    /// <summary>
    /// The vertical unit for 1-dimensional or 3-dimensional coordinate systems.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalAxisUnitID")]
    public string VerticalAxisUnitID { get; set; }

}

/// <summary>
/// The CoordinateSystem authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_CoordinateSystem_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Scope and extent information about the described CRS.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage
{
    /// <summary>
    /// The PreferredUsage authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Usage.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Extent or area of use information.
    /// </summary>
    [JsonPropertyName("Extent")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Extent? Extent { get; set; }

    /// <summary>
    /// Scope declaration.
    /// </summary>
    [JsonPropertyName("Scope")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Scope? Scope { get; set; }

}

/// <summary>
/// The PreferredUsage authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Extent or area of use information.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Extent
{
    /// <summary>
    /// The Preferred Extent authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Extent_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Extent.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The description of the Extent.
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// Southern latitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxSouthBoundLatitude")]
    public double? BoundingBoxSouthBoundLatitude { get; set; }

    /// <summary>
    /// Western longitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxWestBoundLongitude")]
    public double? BoundingBoxWestBoundLongitude { get; set; }

    /// <summary>
    /// Eastern longitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxEastBoundLongitude")]
    public double? BoundingBoxEastBoundLongitude { get; set; }

    /// <summary>
    /// Northern latitude limit of the bounding box in degrees based on WGS 84
    /// </summary>
    [JsonPropertyName("BoundingBoxNorthBoundLatitude")]
    public double? BoundingBoxNorthBoundLatitude { get; set; }

}

/// <summary>
/// The Preferred Extent authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Extent_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}

/// <summary>
/// Scope declaration.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Scope
{
    /// <summary>
    /// The Preferred Scope authority code, corresponding to the ISO19111 ID and 'projjson' id.
    /// </summary>
    [JsonPropertyName("AuthorityCode")]
    public CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Scope_AuthorityCode? AuthorityCode { get; set; }

    /// <summary>
    /// The name of the Scope.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The Preferred Scope authority code, corresponding to the ISO19111 ID and 'projjson' id.
/// </summary>
public class CoordinateReferenceSystem_1_1_0_Data_PreferredUsage_Scope_AuthorityCode
{
    /// <summary>
    /// The authority governing the 'Code'.
    /// </summary>
    [JsonPropertyName("Authority")]
    public string Authority { get; set; }

    /// <summary>
    /// The code assigned by the 'Authority'.
    /// </summary>
    [JsonPropertyName("Code")]
    public int? Code { get; set; }

}
