// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.ReferenceData;

/// <summary>
/// IndexPropertyPathConfiguration contains the de-normalization configuration settings for the Search index. The record id contains the kind so that there is a unique relationship between the kind and the kind's index extensions.
/// </summary>
public class IndexPropertyPathConfiguration_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-IndexPropertyPathConfiguration:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public IndexPropertyPathConfiguration_1_0_0_Data? Data { get; set; }

}

public class IndexPropertyPathConfiguration_1_0_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractReferenceType_1_0_0
{
    /// <summary>
    /// The name of the entity instance.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Alternative names, including historical, by which this entity instance is/has been known.
    /// </summary>
    [JsonPropertyName("NameAlias")]
    public List<AbstractAliasNames_1_0_0> NameAlias { get; set; }

    /// <summary>
    /// Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the "Source" property should identify that source system.
    /// </summary>
    [JsonPropertyName("ID")]
    public string ID { get; set; }

    /// <summary>
    /// By default reference values are considered as 'active'. An absent 'InactiveIndicator' property value means the reference value is in active use. When 'InactiveIndicator' is set true the reverence value is no longer in use and should no longer be offered as a choice.
    /// </summary>
    [JsonPropertyName("InactiveIndicator")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? InactiveIndicator { get; set; }

    /// <summary>
    /// The text which describes a NAME TYPE in detail.
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// The abbreviation or mnemonic for a reference type if defined. Example: WELL and WLBR.
    /// </summary>
    [JsonPropertyName("Code")]
    public string Code { get; set; }

    /// <summary>
    /// Name of the authority, or organisation, which governs the entity value and from which it is sourced.
    /// </summary>
    [JsonPropertyName("AttributionAuthority")]
    public string AttributionAuthority { get; set; }

    /// <summary>
    /// Name, URL, or other identifier of the publication, or repository, of the attribution source organisation from which the entity value is sourced.
    /// </summary>
    [JsonPropertyName("AttributionPublication")]
    public string AttributionPublication { get; set; }

    /// <summary>
    /// The distinct instance of the attribution publication, by version number, sequence number, date of publication, etc., that was used for the entity value.
    /// </summary>
    [JsonPropertyName("AttributionRevision")]
    public string AttributionRevision { get; set; }

    /// <summary>
    /// For reference values published and governed by OSDU: The date and time the record was committed into the OSDU member GitLab reference-values repository. The sole purpose of this date is to optimise the OSDU milestone upgrades. It allows the upgrade code to figure out whether or not the record must be PUT into reference value storage.
    /// </summary>
    [JsonPropertyName("CommitDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CommitDate { get; set; }

    /// <summary>
    /// The list of index property configurations for the specific kind.
    /// </summary>
    [JsonPropertyName("Configurations")]
    public List<IndexPropertyPathConfiguration_1_0_0_Data_Configurations> Configurations { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// One single configuration to derive an Search index property value and assign it to the index 'column' with Name.
/// </summary>
public class IndexPropertyPathConfiguration_1_0_0_Data_Configurations
{
    /// <summary>
    /// The name of the indexed property, i.e., this is the property name used in Search.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// The use case description this configuration satisfies.
    /// </summary>
    [JsonPropertyName("UseCase")]
    public string UseCase { get; set; }

    /// <summary>
    /// Current supported policies are 'ExtractAllMatches' resulting in an array of values or 'ExtractFirstMatch' single value. The policy applies only to the Paths[].ValueExtraction.
    /// </summary>
    [RegularExpression(@"^(ExtractFirstMatch|ExtractAllMatches)$")]
    [JsonPropertyName("Policy")]
    public string Policy { get; set; }

    /// <summary>
    /// The list of path definitions to derive the property value from.
    /// </summary>
    [JsonPropertyName("Paths")]
    public List<IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths> Paths { get; set; }

}

/// <summary>
/// A single path definition to derive a property value from.
/// </summary>
public class IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths
{
    /// <summary>
    /// The specification to extract related objects, from which to derive the ValueExtraction. If this property is empty or absent, the ValueExtraction is done on the current object to be indexed.
    /// </summary>
    [JsonPropertyName("RelatedObjectsSpec")]
    public IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths_RelatedObjectsSpec? RelatedObjectsSpec { get; set; }

    /// <summary>
    /// The instructions from where to derive the value.
    /// </summary>
    [Required]
    [JsonPropertyName("ValueExtraction")]
    public IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths_ValueExtraction ValueExtraction { get; set; }

}

/// <summary>
/// The specification to extract related objects, from which to derive the ValueExtraction. If this property is empty or absent, the ValueExtraction is done on the current object to be indexed.
/// </summary>
public class IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths_RelatedObjectsSpec
{
    /// <summary>
    /// The path to the property containing the ID of the target record to chase. This property is only populated if the property is extracted from a related object, which must be chased. If the property is derived from 'within' the same record, which triggered the indexing, the RelatedObjectID is left absent.
    /// </summary>
    [JsonPropertyName("RelatedObjectID")]
    public string RelatedObjectID { get; set; }

    /// <summary>
    /// The kind or schema id expected as the target object type. This property is only populated if the property is extracted from a related object, which must be chased. If the property is derived from 'within' the same record, which triggered the indexing, the RelatedObjectKind is left absent.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.$")]
    [JsonPropertyName("RelatedObjectKind")]
    public string RelatedObjectKind { get; set; }

    /// <summary>
    /// The direction of the relationship definition seen from the object being indexed.  'ChildToParent' assumes an outgoing relationship with the target record defined in the object being indexed. 'ParentToChildren' assumes that the related objects have a relationship by RelatedObjectID to the id of the record being indexed.
    /// </summary>
    [RegularExpression(@"^(ChildToParent|ParentToChildren)$")]
    [JsonPropertyName("RelationshipDirection")]
    public string RelationshipDirection { get; set; }

    /// <summary>
    /// The property path of the target record data block, which needs subjected to the conditional matching. The data prefix is not required.
    /// </summary>
    [JsonPropertyName("RelatedConditionProperty")]
    public string RelatedConditionProperty { get; set; }

    /// <summary>
    /// The RelatedConditionProperty values, which need to match in order to be accepted as de-normalized value(s). If the Policy is ExtractFirstMatch, the list is prioritized and the first match is accepted as final value. Policy ExtractAllMatches collects all matching values as array.
    /// </summary>
    [JsonPropertyName("RelatedConditionMatches")]
    public List<string> RelatedConditionMatches { get; set; }

}

/// <summary>
/// The instructions from where to derive the value.
/// </summary>
public class IndexPropertyPathConfiguration_1_0_0_Data_Configurations_Paths_ValueExtraction
{
    /// <summary>
    /// The property path of the target record data block, which needs to be subjected to the conditional matching. The data prefix is not required in the path.
    /// </summary>
    [JsonPropertyName("RelatedConditionProperty")]
    public string RelatedConditionProperty { get; set; }

    /// <summary>
    /// The RelatedConditionProperty values, which need to match in order to be accepted as de-normalized value(s). If the Policy is ExtractFirstMatch, the list is prioritized and the first match is accepted as final value. Policy ExtractAllMatches collects all matching values as array.
    /// </summary>
    [JsonPropertyName("RelatedConditionMatches")]
    public List<string> RelatedConditionMatches { get; set; }

    /// <summary>
    /// The path to the property from where to extract the de-normalized value. The data prefix is not required in the path.
    /// </summary>
    [Required]
    [JsonPropertyName("ValuePath")]
    public string ValuePath { get; set; }

}
