// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Osdu.Client.Apis.Legal;

public interface ILegalApiClient
{
    /// <summary>
    /// Gets all LegalTags.
    /// </summary>
    Task<LegalTagDtos> GetLegaltagsAsync(bool? valid = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates the LegalTag for the given `name`.
    /// </summary>
    Task<LegalTagDto> PutLegaltagsAsync(UpdateLegalTag body, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates the LegalTag for the given `name`.
    /// </summary>
    Task<LegalTagDto> PostLegaltagsAsync(LegalTagDto body, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves the invalid LegalTag names with reasons for the given `names`.
    /// </summary>
    Task<InvalidTagsWithReason> PostLegaltagsValidateAsync(RequestLegalTags body, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves the legaltags which matches query criteria or none if there is no match.
    /// </summary>
    Task<LegalTagDtos> PostLegaltagsQueryAsync(QueryLegalTag body, bool? valid = default, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves the LegalTags for the given `names`.
    /// </summary>
    Task<LegalTagDtos> PostLegaltagsBatchRetrieveAsync(RequestLegalTags body, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets LegalTag property values.
    /// </summary>
    Task<ReadablePropertyValues> GetLegaltagsPropertiesAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a LegalTag for the given `name`.
    /// </summary>
    Task<LegalTagDto> GetLegaltagsByNameAsync(string name, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a LegalTag for the given `name`.
    /// </summary>
    Task<string> DeleteLegaltagsByNameAsync(string name, CancellationToken cancellationToken = default);

    /// <summary>
    /// Check LegalTag Compliance Job Status
    /// </summary>
    Task<string> GetJobsUpdateLegalTagStatusAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Version info
    /// </summary>
    Task<VersionInfo> GetInfoAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Readiness Check endpoint
    /// </summary>
    Task<string> GetAhReadinessCheckAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Liveness Check endpoint
    /// </summary>
    Task<string> GetAhLivenessCheckAsync(CancellationToken cancellationToken = default);

}

public partial class LegalApiClient : ILegalApiClient
{
    private readonly HttpClient _httpClient;
    private readonly JsonSerializerOptions _jsonOptions;
    private readonly string _baseUrl;

    public LegalApiClient(HttpClient httpClient)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        _baseUrl = "/api/legal/v1";
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
    }

    /// <summary>
    /// Gets all LegalTags.
    /// </summary>
    public async Task<LegalTagDtos> GetLegaltagsAsync(bool? valid = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (valid.HasValue)
            queryParts.Add($"valid={valid.Value.ToString().ToLowerInvariant()}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/legaltags{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDtos>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Updates the LegalTag for the given `name`.
    /// </summary>
    public async Task<LegalTagDto> PutLegaltagsAsync(UpdateLegalTag body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags";

        using var request = new HttpRequestMessage(HttpMethod.Put, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDto>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Creates the LegalTag for the given `name`.
    /// </summary>
    public async Task<LegalTagDto> PostLegaltagsAsync(LegalTagDto body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDto>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Retrieves the invalid LegalTag names with reasons for the given `names`.
    /// </summary>
    public async Task<InvalidTagsWithReason> PostLegaltagsValidateAsync(RequestLegalTags body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags:validate";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<InvalidTagsWithReason>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Retrieves the legaltags which matches query criteria or none if there is no match.
    /// </summary>
    public async Task<LegalTagDtos> PostLegaltagsQueryAsync(QueryLegalTag body, bool? valid = default, CancellationToken cancellationToken = default)
    {
        var queryParts = new List<string>();
        if (valid.HasValue)
            queryParts.Add($"valid={valid.Value.ToString().ToLowerInvariant()}");
        var queryString = queryParts.Count > 0 ? "?" + string.Join("&", queryParts) : "";
        var requestUrl = $"{_baseUrl}/legaltags:query{queryString}";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDtos>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Retrieves the LegalTags for the given `names`.
    /// </summary>
    public async Task<LegalTagDtos> PostLegaltagsBatchRetrieveAsync(RequestLegalTags body, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags:batchRetrieve";

        using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
        request.Content = JsonContent.Create(body, options: _jsonOptions);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDtos>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Gets LegalTag property values.
    /// </summary>
    public async Task<ReadablePropertyValues> GetLegaltagsPropertiesAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags:properties";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<ReadablePropertyValues>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Gets a LegalTag for the given `name`.
    /// </summary>
    public async Task<LegalTagDto> GetLegaltagsByNameAsync(string name, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags/{name}";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<LegalTagDto>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Deletes a LegalTag for the given `name`.
    /// </summary>
    public async Task<string> DeleteLegaltagsByNameAsync(string name, CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/legaltags/{name}";

        using var request = new HttpRequestMessage(HttpMethod.Delete, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

    /// <summary>
    /// Check LegalTag Compliance Job Status
    /// </summary>
    public async Task<string> GetJobsUpdateLegalTagStatusAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/jobs/updateLegalTagStatus";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

    /// <summary>
    /// Version info
    /// </summary>
    public async Task<VersionInfo> GetInfoAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/info";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadFromJsonAsync<VersionInfo>(_jsonOptions, cancellationToken)
            ?? throw new InvalidOperationException("Response deserialization returned null.");
    }

    /// <summary>
    /// Readiness Check endpoint
    /// </summary>
    public async Task<string> GetAhReadinessCheckAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/_ah/readiness_check";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

    /// <summary>
    /// Liveness Check endpoint
    /// </summary>
    public async Task<string> GetAhLivenessCheckAsync(CancellationToken cancellationToken = default)
    {
        var requestUrl = $"{_baseUrl}/_ah/liveness_check";

        using var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new OsduApiException(response.StatusCode, errorBody, requestUrl);
        }
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }

}
