// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Schema;

/// <summary>
/// Represents a model to Schema Request
/// </summary>
public class SchemaRequest
{
    /// <summary>
    /// Schema identity and metadata
    /// </summary>
    [Required]
    [JsonPropertyName("schemaInfo")]
    public SchemaInfo SchemaInfo { get; set; }

    /// <summary>
    /// The JSON Schema definition as a JSON object
    /// </summary>
    [Required]
    [JsonPropertyName("schema")]
    public string Schema { get; set; }

}
