// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// Information about a series of planned activities.
/// </summary>
public class ActivityPlan_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-ActivityPlan:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public ActivityPlan_1_0_0_Data? Data { get; set; }

}

public class ActivityPlan_1_0_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_0_0, AbstractProject_1_0_0
{
    /// <summary>
    /// A reference to the wellbore that is the subject of this activity plan
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreID")]
    public string WellboreID { get; set; }

    /// <summary>
    /// The activities that compose this plan
    /// </summary>
    [JsonPropertyName("WellPlanningActivities")]
    public List<ActivityPlan_1_0_0_Data_WellPlanningActivities> WellPlanningActivities { get; set; }

    /// <summary>
    /// Name of Activity Plan
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// Information regarding an individual activity that is part of the ActivityPlan
/// </summary>
public class ActivityPlan_1_0_0_Data_WellPlanningActivities
{
    /// <summary>
    /// A name given to this activity
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Identifier of the activity
    /// </summary>
    [Required]
    [JsonPropertyName("ActivityID")]
    public string ActivityID { get; set; }

    /// <summary>
    /// The depth range over which the the activity takes place
    /// </summary>
    [JsonPropertyName("DepthRange")]
    public ActivityPlan_1_0_0_Data_WellPlanningActivities_DepthRange? DepthRange { get; set; }

    /// <summary>
    /// The parent activity to this activity
    /// </summary>
    [JsonPropertyName("ParentID")]
    public string ParentID { get; set; }

    /// <summary>
    /// The activity code of the activity
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ActivityCode:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ActivityCodeID")]
    public string ActivityCodeID { get; set; }

    /// <summary>
    /// The preceding activity in the plan
    /// </summary>
    [JsonPropertyName("PredecessorsID")]
    public string PredecessorsID { get; set; }

    /// <summary>
    /// The expected productive time of the activity - if "clean time probability" distribution is populated then this should be the expected value of the distribution
    /// </summary>
    [JsonPropertyName("ProductiveTimeDuration")]
    public double? ProductiveTimeDuration { get; set; }

    /// <summary>
    /// The expected duration of the non productive time of the activity
    /// </summary>
    [JsonPropertyName("NonProductiveTimeDuration")]
    public double? NonProductiveTimeDuration { get; set; }

    /// <summary>
    /// Statistics that define the expected productivity time of this activity
    /// </summary>
    [JsonPropertyName("ProductiveTimeStatistics")]
    public List<ActivityPlan_1_0_0_Data_WellPlanningActivities_ProductiveTimeStatistics> ProductiveTimeStatistics { get; set; }

    /// <summary>
    /// Statistics that define the non productive time of this activity
    /// </summary>
    [JsonPropertyName("NonProductiveTimeStatistics")]
    public List<ActivityPlan_1_0_0_Data_WellPlanningActivities_NonProductiveTimeStatistics> NonProductiveTimeStatistics { get; set; }

    /// <summary>
    /// Statistics that define the rate of penetration of this activity
    /// </summary>
    [JsonPropertyName("RateOfPenetrationStatistics")]
    public List<ActivityPlan_1_0_0_Data_WellPlanningActivities_RateOfPenetrationStatistics> RateOfPenetrationStatistics { get; set; }

    /// <summary>
    /// Free form comments associated with this activity
    /// </summary>
    [JsonPropertyName("Comment")]
    public string Comment { get; set; }

    /// <summary>
    /// Reference to objects that is defined within the context of a wellbore. The WITSML 1.4.1 standard has only one object reference, but a risk may related with multiple objects.
    /// </summary>
    [JsonPropertyName("ObjectReferenceIDs")]
    public List<string> ObjectReferenceIDs { get; set; }

    /// <summary>
    /// the catalog version of this activity
    /// </summary>
    [JsonPropertyName("ActivityCodeCatalogVersion")]
    public string ActivityCodeCatalogVersion { get; set; }

    /// <summary>
    /// The activity level of this activity. Levels go from L1 to L6
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ActivityLevel:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ActivityLevel")]
    public string ActivityLevel { get; set; }

    /// <summary>
    /// Date/Time the activity is planned to start
    /// </summary>
    [JsonPropertyName("PlannedStartTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? PlannedStartTime { get; set; }

    /// <summary>
    /// Date/Time the activity is planned to end
    /// </summary>
    [JsonPropertyName("PlannedEndTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? PlannedEndTime { get; set; }

    /// <summary>
    /// Overall duration as planned for the activity
    /// </summary>
    [JsonPropertyName("PlannedDuration")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? PlannedDuration { get; set; }

    /// <summary>
    /// A reference to the object that holds the information about the risks that apply to the activity
    /// </summary>
    [JsonPropertyName("RiskIDs")]
    public List<string> RiskIDs { get; set; }

    /// <summary>
    /// Flag used to indicates this particular activity is optional in the plan.
    /// </summary>
    [JsonPropertyName("IsOptional")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsOptional { get; set; }

}

/// <summary>
/// The depth range over which the the activity takes place
/// </summary>
public class ActivityPlan_1_0_0_Data_WellPlanningActivities_DepthRange
{
    /// <summary>
    /// The depth of the hole at the start of the activity. Depth relative to Planned wellbore ZDP. Navigate via WellboreID to the side-car WellPlanningWellbore, which holds the depth reference in data.VerticalMeasurement.
    /// </summary>
    [JsonPropertyName("HoleDepthStart")]
    public double? HoleDepthStart { get; set; }

    /// <summary>
    /// The depth of the hole at the end of the activity. Depth relative to Planned wellbore ZDP. Navigate via WellboreID to the side-car WellPlanningWellbore, which holds the depth reference in data.VerticalMeasurement.
    /// </summary>
    [JsonPropertyName("HoleDepthEnd")]
    public double? HoleDepthEnd { get; set; }

    /// <summary>
    /// The start depth of the activity. Depth relative to Planned wellbore ZDP. Navigate via WellboreID to the side-car WellPlanningWellbore, which holds the depth reference in data.VerticalMeasurement.
    /// </summary>
    [JsonPropertyName("ActivityDepthStart")]
    public double? ActivityDepthStart { get; set; }

    /// <summary>
    /// The end depth of the activity. Depth relative to Planned wellbore ZDP. Navigate via WellboreID to the side-car WellPlanningWellbore, which holds the depth reference in data.VerticalMeasurement.
    /// </summary>
    [JsonPropertyName("ActivityDepthEnd")]
    public double? ActivityDepthEnd { get; set; }

}

/// <summary>
/// Structure that describes a individual statistic record of the operations from an activity.
/// </summary>
public class ActivityPlan_1_0_0_Data_WellPlanningActivities_ProductiveTimeStatistics
{
    /// <summary>
    /// Record of the statistic estimation
    /// </summary>
    [Required]
    [JsonPropertyName("StatisticRecord")]
    public double StatisticRecord { get; set; }

    /// <summary>
    /// Identifier of the probability type the value is describing
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-PPFGCurveProbability:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProbabilityTypeID")]
    public string ProbabilityTypeID { get; set; }

}

/// <summary>
/// Structure that describes a individual statistic record of the operations from an activity.
/// </summary>
public class ActivityPlan_1_0_0_Data_WellPlanningActivities_NonProductiveTimeStatistics
{
    /// <summary>
    /// Record of the statistic estimation
    /// </summary>
    [Required]
    [JsonPropertyName("StatisticRecord")]
    public double StatisticRecord { get; set; }

    /// <summary>
    /// Identifier of the probability type the value is describing
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-PPFGCurveProbability:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProbabilityTypeID")]
    public string ProbabilityTypeID { get; set; }

}

/// <summary>
/// Individual Statistics that define the rate of penetration of an activity
/// </summary>
public class ActivityPlan_1_0_0_Data_WellPlanningActivities_RateOfPenetrationStatistics
{
    /// <summary>
    /// Record of the statistic estimation
    /// </summary>
    [Required]
    [JsonPropertyName("StatisticRecord")]
    public double StatisticRecord { get; set; }

    /// <summary>
    /// Identifier of the probability type the value is describing
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-PPFGCurveProbability:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProbabilityTypeID")]
    public string ProbabilityTypeID { get; set; }

}
