// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// System-level object containing business and technical metadata for an external OSDU-compliant data source, used for registration of that source within the OSDU external data framework.
/// </summary>
public class ConnectedSourceRegistryEntry_1_1_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-ConnectedSourceRegistryEntry:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public ConnectedSourceRegistryEntry_1_1_0Data? Data { get; set; }

}

public class ConnectedSourceRegistryEntry_1_1_0Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_1_0
{
    /// <summary>
    /// Descriptive label given to the data source. This could be the name of an organisation and/or the name of a specific database or system.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Additional information/description about the data source
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// Flag that determines whether the external source has a full OSDU implementation (true) or a wrapper facade over proprietary APIs (false)
    /// </summary>
    [JsonPropertyName("FullOSDUImplementationIndicator")]
    public bool? FullOSDUImplementationIndicator { get; set; }

    /// <summary>
    /// References to applicable agreements governing the use of the data source
    /// </summary>
    [JsonPropertyName("AgreementIDs")]
    public List<string> AgreementIDs { get; set; }

    /// <summary>
    /// List of security schemes available for use in authorizing against OSDU-compliant APIs of a connected data source.
    /// </summary>
    [JsonPropertyName("SecuritySchemes")]
    public List<ConnectedSourceRegistryEntry_1_1_0DataSecuritySchemes> SecuritySchemes { get; set; }

    /// <summary>
    /// List of SMTP server schemes available for use in mailing the detailed EDS's report.
    /// </summary>
    [JsonPropertyName("SmtpSchemes")]
    public List<ConnectedSourceRegistryEntry_1_1_0DataSmtpSchemes> SmtpSchemes { get; set; }

    /// <summary>
    /// Connectivity information for Airflow endpoints to get more information of Manifest Ingestion.
    /// </summary>
    [JsonPropertyName("AirflowStableAPIUrl")]
    public string AirflowStableAPIUrl { get; set; }

    /// <summary>
    /// Identifier of the organisation that the registered source belongs to.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SourceOrganisationID")]
    public string SourceOrganisationID { get; set; }

    /// <summary>
    /// Temporary property awaiting a external reference-value mapping framework. A generic dictionary of string reference-data as keys mapping to reference-value as string value. Only predefined reference-data and its values are permitted.
    /// </summary>
    [JsonPropertyName("ReferenceValueMappings")]
    public object? ReferenceValueMappings { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// Metadata used to retrieve or generate credentials needed for authorization.
/// </summary>
public class ConnectedSourceRegistryEntry_1_1_0DataSecuritySchemes
{
    /// <summary>
    /// Unique name given to a security scheme
    /// </summary>
    [Required]
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Type of security schema
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SecuritySchemeType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TypeID")]
    public string TypeID { get; set; }

    /// <summary>
    /// OAuth2 flow, or grant type
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-OAuth2FlowType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("FlowTypeID")]
    public string FlowTypeID { get; set; }

    /// <summary>
    /// Url the identity provider will send the token to in OAuth2 authorization code flows
    /// </summary>
    [JsonPropertyName("CallbackUrl")]
    public string CallbackUrl { get; set; }

    /// <summary>
    /// Authorization endpoint of the identity provider used in OAuth2 flows
    /// </summary>
    [JsonPropertyName("AuthorizationUrl")]
    public string AuthorizationUrl { get; set; }

    /// <summary>
    /// Token endpoint of the identity provider used in OAuth2 flows
    /// </summary>
    [JsonPropertyName("TokenUrl")]
    public string TokenUrl { get; set; }

    /// <summary>
    /// Key for obtaining the space-delimited scopes list for use in OAuth2 flows from the secret repository
    /// </summary>
    [JsonPropertyName("ScopesKeyName")]
    public string ScopesKeyName { get; set; }

    /// <summary>
    /// DEPRECATED: Superseded  by ClientIDKeyName. Client ID
    /// </summary>
    [JsonPropertyName("ClientID")]
    public string ClientID { get; set; }

    /// <summary>
    /// Key for obtaining the client secret for use in OAuth2 flows from the secret repository
    /// </summary>
    [JsonPropertyName("ClientSecretKeyName")]
    public string ClientSecretKeyName { get; set; }

    /// <summary>
    /// Audience used in OAuth2 flows
    /// </summary>
    [JsonPropertyName("Audience")]
    public string Audience { get; set; }

    /// <summary>
    /// Key for obtaining a refresh token from the secret repository
    /// </summary>
    [JsonPropertyName("RefreshTokenKeyName")]
    public string RefreshTokenKeyName { get; set; }

    /// <summary>
    /// Key for obtaining an access token from the secret repository
    /// </summary>
    [JsonPropertyName("AccessTokenKeyName")]
    public string AccessTokenKeyName { get; set; }

    /// <summary>
    /// Key for obtaining an API key from the secret repository
    /// </summary>
    [JsonPropertyName("APIKeyKeyName")]
    public string APIKeyKeyName { get; set; }

    /// <summary>
    /// Key for obtaining Username from the secret repository
    /// </summary>
    [JsonPropertyName("UsernameKeyName")]
    public string UsernameKeyName { get; set; }

    /// <summary>
    /// Key for obtaining Password from the secret repository
    /// </summary>
    [JsonPropertyName("PasswordKeyName")]
    public string PasswordKeyName { get; set; }

    /// <summary>
    /// Url of the secret repository containing secrets for this security scheme
    /// </summary>
    [JsonPropertyName("SecretRepoUrl")]
    public string SecretRepoUrl { get; set; }

    /// <summary>
    /// Key for obtaining the client id for use in the OAuth2 flows from the secret repository
    /// </summary>
    [JsonPropertyName("ClientIDKeyName")]
    public string ClientIDKeyName { get; set; }

}

/// <summary>
/// Metadata used to mail the EDS's Report.
/// </summary>
public class ConnectedSourceRegistryEntry_1_1_0DataSmtpSchemes
{
    /// <summary>
    /// Unique name given to a SMTP scheme.
    /// </summary>
    [Required]
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Key for the SMTP user.
    /// </summary>
    [JsonPropertyName("SmtpUserKeyName")]
    public string SmtpUserKeyName { get; set; }

    /// <summary>
    /// Key for the SMTP password.
    /// </summary>
    [JsonPropertyName("SmtpPasswordKeyName")]
    public string SmtpPasswordKeyName { get; set; }

    /// <summary>
    /// Sender's mail address.
    /// </summary>
    [JsonPropertyName("SmtpSenderMail")]
    public string SmtpSenderMail { get; set; }

    /// <summary>
    /// Timeout time for the SMTP server.
    /// </summary>
    [JsonPropertyName("SmtpTimeOut")]
    public int? SmtpTimeOut { get; set; }

    /// <summary>
    /// Limit to retry for the connection.
    /// </summary>
    [JsonPropertyName("SmtpRetryLimit")]
    public int? SmtpRetryLimit { get; set; }

    /// <summary>
    /// Key for the SMTP host.
    /// </summary>
    [JsonPropertyName("SmtpHostKeyName")]
    public string SmtpHostKeyName { get; set; }

    /// <summary>
    /// Type of protocol for connection.
    /// </summary>
    [JsonPropertyName("SmtpStartTLS")]
    public bool? SmtpStartTLS { get; set; }

    /// <summary>
    /// Type of protocol for connection.
    /// </summary>
    [JsonPropertyName("SmtpSSL")]
    public bool? SmtpSSL { get; set; }

    /// <summary>
    /// SMTP Port for the connection,its different for SSL/StartTLS.
    /// </summary>
    [JsonPropertyName("SmtpPort")]
    public int? SmtpPort { get; set; }

    /// <summary>
    /// List of receiver's mail addresses.
    /// </summary>
    [JsonPropertyName("SmtpReceiverMail")]
    public List<string> SmtpReceiverMail { get; set; }

    /// <summary>
    /// Start date from which report is required.
    /// </summary>
    [JsonPropertyName("ReportStartDate")]
    public DateTimeOffset ReportStartDate { get; set; }

    /// <summary>
    /// End date till report is required.
    /// </summary>
    [JsonPropertyName("ReportEndDate")]
    public DateTimeOffset ReportEndDate { get; set; }

    /// <summary>
    /// Email Trigger Frequency for the EDS report, cron job format
    /// </summary>
    [JsonPropertyName("EmailTriggerFrequency")]
    public string EmailTriggerFrequency { get; set; }

}
