// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// Scheduling, data fetch, and ingestion configuration for automated jobs against a registered connected data source.
/// </summary>
public class ConnectedSourceDataJob_1_5_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-ConnectedSourceDataJob:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public ConnectedSourceDataJob_1_5_0Data? Data { get; set; }

}

public class ConnectedSourceDataJob_1_5_0Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_2_0, AbstractProject_1_0_0, AbstractProjectActivity_1_2_0
{
    /// <summary>
    /// Descriptive label given to a scheduled job.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// ID reference of the parent Connected Source Registry Entry
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-ConnectedSourceRegistryEntry:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ConnectedSourceRegistryEntryID")]
    public string ConnectedSourceRegistryEntryID { get; set; }

    /// <summary>
    /// Indicates if a scheduled job is active (will be executed) or not (won't be executed)
    /// </summary>
    [JsonPropertyName("ActiveIndicator")]
    public bool? ActiveIndicator { get; set; }

    /// <summary>
    /// The data type/schema/kind of data being retrieved form the external source. The returned value should validate against the corresponding registered schema in the OSDU schema service.
    /// </summary>
    [JsonPropertyName("FetchKind")]
    public string FetchKind { get; set; }

    /// <summary>
    /// Filter applied to the data fetch request, using data members in the FetchKind schema.
    /// </summary>
    [JsonPropertyName("Filter")]
    public string Filter { get; set; }

    /// <summary>
    /// ID of the external partition containing the desired data
    /// </summary>
    [JsonPropertyName("ConnectedSourceDataPartitionID")]
    public string ConnectedSourceDataPartitionID { get; set; }

    /// <summary>
    /// Schedule this job should run on, in CRON format
    /// </summary>
    [JsonPropertyName("ScheduleUTC")]
    public string ScheduleUTC { get; set; }

    /// <summary>
    /// Consumer partition the incoming data will be placed in.
    /// </summary>
    [JsonPropertyName("OnIngestionDataPartitionID")]
    public string OnIngestionDataPartitionID { get; set; }

    /// <summary>
    /// DEPRECATED: Superseded by the contents of appropriate parameters in an ActivityTemplate instance identified by data.ActivityTemplateID. In earlier versions: List of workflows and their configuration used in this scheduled job
    /// </summary>
    [JsonPropertyName("Workflows")]
    public List<ConnectedSourceDataJob_1_5_0DataWorkflows> Workflows { get; set; }

    [JsonPropertyName("OnIngestionLegalTags")]
    public AbstractLegalTags_1_0_0? OnIngestionLegalTags { get; set; }

    [JsonPropertyName("OnIngestionAcl")]
    public AbstractAccessControlList_1_0_0? OnIngestionAcl { get; set; }

    /// <summary>
    /// The last successful run date of the job (UTC)
    /// </summary>
    [JsonPropertyName("LastSuccessfulRunDateUTC")]
    public DateTimeOffset LastSuccessfulRunDateUTC { get; set; }

    /// <summary>
    /// The maximum number of records to be processed in this job.
    /// </summary>
    [JsonPropertyName("LimitRecords")]
    public int? LimitRecords { get; set; }

    /// <summary>
    /// A temporary solution before these references are stored in a related, external record for scalability: The data type/schema/kind of data being retrieved form the external source. The failed records list which is retrieved from the external source.
    /// </summary>
    [JsonPropertyName("FailedRecords")]
    public List<string> FailedRecords { get; set; }

    /// <summary>
    /// Consumer schema authority for the incoming data will be placed in.
    /// </summary>
    [JsonPropertyName("OnIngestionSchemaAuthority")]
    public string OnIngestionSchemaAuthority { get; set; }

    /// <summary>
    /// The maximum create/update time for data records (UTC).
    /// </summary>
    [JsonPropertyName("CreateTimeMax")]
    public DateTimeOffset CreateTimeMax { get; set; }

    /// <summary>
    /// Source system schema authority.
    /// </summary>
    [JsonPropertyName("ConnectedSourceSchemaAuthority")]
    public string ConnectedSourceSchemaAuthority { get; set; }

    /// <summary>
    /// Start time of the records to be fetched from the source system.
    /// </summary>
    [JsonPropertyName("FetchStartDateTime")]
    public DateTimeOffset FetchStartDateTime { get; set; }

    /// <summary>
    /// End time of the records to be fetched from the source system.
    /// </summary>
    [JsonPropertyName("FetchEndDateTime")]
    public DateTimeOffset FetchEndDateTime { get; set; }

    /// <summary>
    /// A fixed dummy master ID is set in advance and will be used if the master record is unavailable in the consumer system. Multiple master ids can be defined as array members; ids are defined without data-partition example: 'master-data--Well:DummyWell'.
    /// </summary>
    [JsonPropertyName("ParentDataMappingDummyMasterIDs")]
    public List<string> ParentDataMappingDummyMasterIDs { get; set; }

    /// <summary>
    /// Indicates if the dummy parent data mapping should be considered or not, by default it will be false (and false if absent), if true ParentDataMappingDummyMasterIDs should be set.
    /// </summary>
    [JsonPropertyName("IsDummyParentMappingEnabled")]
    public bool? IsDummyParentMappingEnabled { get; set; }

    /// <summary>
    /// The wait time, in seconds, for the eds_Ingest DAG run upon completion of the Manifest Ingestion (osdu_ingest) DAG run, used to retrieve details from the XCom summary.
    /// </summary>
    [JsonPropertyName("EdsIngestWaitTime")]
    public double? EdsIngestWaitTime { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// A workflow configuration in the context of a scheduled job.
/// </summary>
public class ConnectedSourceDataJob_1_5_0DataWorkflows
{
    /// <summary>
    /// Tag given to a workflow category, such as Fetch, Ingest, Delivery
    /// </summary>
    [JsonPropertyName("Tag")]
    public string Tag { get; set; }

    /// <summary>
    /// Allows creation of a specific handler DAG for the source type
    /// </summary>
    [JsonPropertyName("Handler")]
    public string Handler { get; set; }

    /// <summary>
    /// Name value or object Id
    /// </summary>
    [JsonPropertyName("Parameters")]
    public List<ConnectedSourceDataJob_1_5_0DataWorkflowsParameters> Parameters { get; set; }

    /// <summary>
    /// Data source endpoint used in workflow
    /// </summary>
    [JsonPropertyName("Url")]
    public string Url { get; set; }

    /// <summary>
    /// Reference name for the security scheme in the ConnectedSourceRegistryEntry document this scheduled job belongs to.
    /// </summary>
    [Required]
    [JsonPropertyName("SecuritySchemeName")]
    public string SecuritySchemeName { get; set; }

}

/// <summary>
/// Parameter name value pair.
/// </summary>
public class ConnectedSourceDataJob_1_5_0DataWorkflowsParameters
{
    /// <summary>
    /// Name of the parameter the handler expects
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Value of the parameter the handler expects
    /// </summary>
    [JsonPropertyName("Value")]
    public string Value { get; set; }

}
