// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// Describes the physical structures for a borehole
/// </summary>
public class WellboreArchitecture_1_2_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-WellboreArchitecture:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public WellboreArchitecture_1_2_0Data? Data { get; set; }

}

public class WellboreArchitecture_1_2_0Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_2_0
{
    /// <summary>
    /// A reference to the wellbore that is the subject of this activity plan
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreID")]
    public string WellboreID { get; set; }

    /// <summary>
    /// Description of the Hole Sections for this architecture
    /// </summary>
    [JsonPropertyName("HoleSectionIDs")]
    public List<string> HoleSectionIDs { get; set; }

    /// <summary>
    /// Description of the Installed tubular associated to this architecture
    /// </summary>
    [JsonPropertyName("InstalledTubulars")]
    public List<WellboreArchitecture_1_2_0DataInstalledTubulars> InstalledTubulars { get; set; }

    /// <summary>
    /// Name of Wellbore Architecture
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// Geometrical Description of tubular assembly as installed in the wellbore
/// </summary>
public class WellboreArchitecture_1_2_0DataInstalledTubulars
{
    /// <summary>
    /// The measured depth at the top of the tubular
    /// </summary>
    [JsonPropertyName("MeasuredDepthTop")]
    public double? MeasuredDepthTop { get; set; }

    /// <summary>
    /// The measured depth at the base of the tubular
    /// </summary>
    [JsonPropertyName("MeasuredDepthBase")]
    public double? MeasuredDepthBase { get; set; }

    /// <summary>
    /// The error associated with the measured depth at the top of the tubular
    /// </summary>
    [JsonPropertyName("MeasuredDepthErrorTop")]
    public double? MeasuredDepthErrorTop { get; set; }

    /// <summary>
    /// The  error associated with the measured depth at the base of the tubular
    /// </summary>
    [JsonPropertyName("MeasuredDepthErrorBase")]
    public double? MeasuredDepthErrorBase { get; set; }

    /// <summary>
    /// Identifier of the tubular assembly actually installed or to be installed
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:(master-data\-\-TubularAssembly|work-product-component\-\-TubularAssembly):[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TubularAssemblyID")]
    public string TubularAssemblyID { get; set; }

}
