// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// A hole in the ground extending from a point at the earth's surface to the maximum point of penetration.
/// </summary>
public class Wellbore_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public Wellbore_1_0_0_Data? Data { get; set; }

}

public class Wellbore_1_0_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_0_0, AbstractFacility_1_0_0
{
    /// <summary>
    /// Alternative names, including historical, by which this master data is/has been known (it should include all the identifiers).
    /// </summary>
    [JsonPropertyName("NameAliases")]
    public List<AbstractAliasNames_1_0_0> NameAliases { get; set; }

    /// <summary>
    /// List of geographic entities which provide context to the master data. This may include multiple types or multiple values of the same type.
    /// </summary>
    [JsonPropertyName("GeoContexts")]
    public List<AbstractGeoContext_1_0_0> GeoContexts { get; set; }

    [JsonPropertyName("SpatialLocation")]
    public AbstractSpatialLocation_1_0_0? SpatialLocation { get; set; }

    /// <summary>
    /// This describes the reason that caused the creation of a new version of this master data.
    /// </summary>
    [JsonPropertyName("VersionCreationReason")]
    public string VersionCreationReason { get; set; }

    /// <summary>
    /// Describes a master-data record's overall suitability for general business consumption based on data quality. Clarifications: Since Certified is the highest classification of suitable quality, any further change or versioning of a Certified record should be carefully considered and justified. If a Technical Assurance value is not populated then one can assume the data has not been evaluated or its quality is unknown (=Unevaluated). Technical Assurance values are not intended to be used for the identification of a single "preferred" or "definitive" record by comparison with other records.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-TechnicalAssuranceType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TechnicalAssuranceTypeID")]
    public string TechnicalAssuranceTypeID { get; set; }

    /// <summary>
    /// Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the "Source" property should identify that source system.
    /// </summary>
    [JsonPropertyName("FacilityID")]
    public string FacilityID { get; set; }

    /// <summary>
    /// The definition of a kind of capability to perform a business function or a service.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-FacilityType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("FacilityTypeID")]
    public string FacilityTypeID { get; set; }

    /// <summary>
    /// The history of operator organizations of the facility.
    /// </summary>
    [JsonPropertyName("FacilityOperators")]
    public List<AbstractFacilityOperator_1_0_0> FacilityOperators { get; set; }

    /// <summary>
    /// A initial operator organization ID; the organization ID may also be found in the FacilityOperatorOrganisationID of the FacilityOperator array providing the actual dates.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("InitialOperatorID")]
    public string InitialOperatorID { get; set; }

    /// <summary>
    /// The current operator organization ID; the organization ID may also be found in the FacilityOperatorOrganisationID of the FacilityOperator array providing the actual dates.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CurrentOperatorID")]
    public string CurrentOperatorID { get; set; }

    /// <summary>
    /// The main source of the header information.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DataSourceOrganisationID")]
    public string DataSourceOrganisationID { get; set; }

    /// <summary>
    /// Identifies the Facility's general location as being onshore vs. offshore.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-OperatingEnvironment:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("OperatingEnvironmentID")]
    public string OperatingEnvironmentID { get; set; }

    /// <summary>
    /// Name of the Facility.
    /// </summary>
    [JsonPropertyName("FacilityName")]
    public string FacilityName { get; set; }

    /// <summary>
    /// DEPRECATED: please use data.NameAliases. Alternative names, including historical, by which this facility is/has been known.
    /// </summary>
    [JsonPropertyName("FacilityNameAliases")]
    public List<AbstractAliasNames_1_0_0> FacilityNameAliases { get; set; }

    /// <summary>
    /// The history of life cycle states the facility has been through.
    /// </summary>
    [JsonPropertyName("FacilityStates")]
    public List<AbstractFacilityState_1_0_0> FacilityStates { get; set; }

    /// <summary>
    /// A list of key facility events.
    /// </summary>
    [JsonPropertyName("FacilityEvents")]
    public List<AbstractFacilityEvent_1_0_0> FacilityEvents { get; set; }

    /// <summary>
    /// facilitySpecification maintains the specification like slot name, wellbore drilling permit number, rig name etc.
    /// </summary>
    [JsonPropertyName("FacilitySpecifications")]
    public List<AbstractFacilitySpecification_1_0_0> FacilitySpecifications { get; set; }

    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Well:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellID")]
    public string WellID { get; set; }

    /// <summary>
    /// A number that indicates the order in which wellbores were drilled.
    /// </summary>
    [JsonPropertyName("SequenceNumber")]
    public int? SequenceNumber { get; set; }

    /// <summary>
    /// List of all depths and elevations pertaining to the wellbore, like, plug back measured depth, total measured depth, KB elevation
    /// </summary>
    [JsonPropertyName("VerticalMeasurements")]
    public List<Wellbore_1_0_0_Data_VerticalMeasurements> VerticalMeasurements { get; set; }

    /// <summary>
    /// The history of drilling reasons of the wellbore.
    /// </summary>
    [JsonPropertyName("DrillingReasons")]
    public List<AbstractWellboreDrillingReason_1_0_0> DrillingReasons { get; set; }

    /// <summary>
    /// This is a pointer to the parent wellbore. The wellbore that starts from top has no parent.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("KickOffWellbore")]
    public string KickOffWellbore { get; set; }

    /// <summary>
    /// Describes the predominant shapes the wellbore path can follow if deviated from vertical. Sample Values: Horizontal, Vertical, Directional.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-WellboreTrajectoryType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TrajectoryTypeID")]
    public string TrajectoryTypeID { get; set; }

    /// <summary>
    /// SRN of Wellbore Trajectory which is considered the authoritative or preferred version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellboreTrajectory:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DefinitiveTrajectoryID")]
    public string DefinitiveTrajectoryID { get; set; }

    /// <summary>
    /// The Formation of interest for which the Wellbore is drilled to interact with. The Wellbore may terminate in a lower formation if the requirement is to drill through the entirety of the target formation, therefore this is not necessarily the Formation at TD.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-GeologicalFormation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TargetFormation")]
    public string TargetFormation { get; set; }

    /// <summary>
    /// The primary material injected/produced from the wellbore.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-MaterialType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PrimaryMaterialID")]
    public string PrimaryMaterialID { get; set; }

    /// <summary>
    /// The default datum reference point, or zero depth point, used to determine other points vertically in a wellbore.  References an entry in the Vertical Measurements array of this wellbore.
    /// </summary>
    [JsonPropertyName("DefaultVerticalMeasurementID")]
    public string DefaultVerticalMeasurementID { get; set; }

    [JsonPropertyName("ProjectedBottomHoleLocation")]
    public AbstractSpatialLocation_1_0_0? ProjectedBottomHoleLocation { get; set; }

    [JsonPropertyName("GeographicBottomHoleLocation")]
    public AbstractSpatialLocation_1_0_0? GeographicBottomHoleLocation { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

public class Wellbore_1_0_0_Data_VerticalMeasurements : AbstractFacilityVerticalMeasurement_1_0_0
{
    /// <summary>
    /// The ID for a distinct vertical measurement within the Wellbore VerticalMeasurements array so that it may be referenced by other vertical measurements if necessary.
    /// </summary>
    [JsonPropertyName("VerticalMeasurementID")]
    public string VerticalMeasurementID { get; set; }

}
