// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.MasterData;

/// <summary>
/// A planned wellbore extending from a point at the earth's surface to the maximum point of penetration (planned total depth).
/// </summary>
public class WellPlanningWellbore_1_4_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-WellPlanningWellbore:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public WellPlanningWellbore_1_4_0_Data? Data { get; set; }

}

public class WellPlanningWellbore_1_4_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractMaster_1_2_0
{
    /// <summary>
    /// Alternative names, including historical, by which this master data is/has been known (it should include all the identifiers).
    /// </summary>
    [JsonPropertyName("NameAliases")]
    public List<AbstractAliasNames_1_0_0> NameAliases { get; set; }

    /// <summary>
    /// List of geographic entities which provide context to the master data. This may include multiple types or multiple values of the same type.
    /// </summary>
    [JsonPropertyName("GeoContexts")]
    public List<AbstractGeoContext_1_0_0> GeoContexts { get; set; }

    [JsonPropertyName("SpatialLocation")]
    public AbstractSpatialLocation_1_1_0? SpatialLocation { get; set; }

    /// <summary>
    /// This describes the reason that caused the creation of a new version of this master data.
    /// </summary>
    [JsonPropertyName("VersionCreationReason")]
    public string VersionCreationReason { get; set; }

    /// <summary>
    /// DEPRECATED: (in favor of more nuanced TechnicalAssurances[] array) Describes a master-data record's overall suitability for general business consumption based on data quality. Clarifications: Since Certified is the highest classification of suitable quality, any further change or versioning of a Certified record should be carefully considered and justified. If a Technical Assurance value is not populated then one can assume the data has not been evaluated or its quality is unknown (=Unevaluated). Technical Assurance values are not intended to be used for the identification of a single "preferred" or "definitive" record by comparison with other records.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-TechnicalAssuranceType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TechnicalAssuranceTypeID")]
    public string TechnicalAssuranceTypeID { get; set; }

    /// <summary>
    /// Describes a record's overall suitability for general business consumption in context of one or more workflows/personas based on data quality and reviewer's decisions. Clarifications: Since Certified is the highest classification of suitable quality, any further change or versioning of a Certified record should be carefully considered and justified. If a Technical Assurance value is not populated then one can assume the data has not been evaluated or its quality is unknown (=Unevaluated). Technical Assurance values are not intended to be used for the identification of a single "preferred" or "definitive" record by comparison with other records.
    /// </summary>
    [JsonPropertyName("TechnicalAssurances")]
    public List<AbstractTechnicalAssurance_1_2_0> TechnicalAssurances { get; set; }

    /// <summary>
    /// Identifier of the parent wellbore.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreID")]
    public string WellboreID { get; set; }

    /// <summary>
    /// Identifier of the parent well side-car for the well planning domain.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-WellPlanningWell:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellPlanningWellID")]
    public string WellPlanningWellID { get; set; }

    /// <summary>
    /// A reference to the objects that holds the information about the definitive version of the different survey programs associated with the wellbore
    /// </summary>
    [JsonPropertyName("SurveyProgramIDs")]
    public List<string> SurveyProgramIDs { get; set; }

    /// <summary>
    /// The drill targets associated with this definitive Drilling Program
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-GeometricTargetSet:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TargetID")]
    public string TargetID { get; set; }

    /// <summary>
    /// The formation markers associated with the definitive Drilling Program
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellboreMarkerSet:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreMarkerSetID")]
    public string WellboreMarkerSetID { get; set; }

    /// <summary>
    /// A reference to the descriptive object that holds the information about the planned lithology associated with the wellbore
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-PlannedLithology:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PlannedLithologyID")]
    public string PlannedLithologyID { get; set; }

    /// <summary>
    /// The definitive description of the hole section associated with this wellbore. If the wellbore has more than  one hole section please use the PlannedHoleSections array.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-HoleSection:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("HoleSectionID")]
    public string HoleSectionID { get; set; }

    /// <summary>
    /// A reference to the PPFGDataset that holds the information about the pore pressure associated with the definitive drilling program
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-PPFGDataset:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PPFGDatasetID")]
    public string PPFGDatasetID { get; set; }

    /// <summary>
    /// Name of Well Planning wellbore. Derived from the record identified by WellboreID.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    [JsonPropertyName("VerticalMeasurement")]
    public AbstractFacilityVerticalMeasurement_1_0_0? VerticalMeasurement { get; set; }

    /// <summary>
    /// A reference to a set of one or more HoleSections associated to the planned Wellbore.
    /// </summary>
    [JsonPropertyName("PlannedHoleSections")]
    public List<string> PlannedHoleSections { get; set; }

    /// <summary>
    /// A reference to a set of one or more CasingDesigns associated to the planned Wellbore.
    /// </summary>
    [JsonPropertyName("PlannedCasingDesigns")]
    public List<string> PlannedCasingDesigns { get; set; }

    /// <summary>
    /// A reference to the Fluids Program that holds the planned fluids for the wellbore
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-FluidsProgram:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("FluidsProgramID")]
    public string FluidsProgramID { get; set; }

    /// <summary>
    /// A reference to the Well Activity Program that holds the planned programs for each phase of the Wellbore
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-WellActivityProgram:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PlannedWellActivityProgramID")]
    public string PlannedWellActivityProgramID { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}
