// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.IngestionWorkflowService.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VersionInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The artifactId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArtifactId { get; set; }
#nullable restore
#else
        public string ArtifactId { get; set; }
#endif
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The buildTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildTime { get; set; }
#nullable restore
#else
        public string BuildTime { get; set; }
#endif
        /// <summary>The commitId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitId { get; set; }
#nullable restore
#else
        public string CommitId { get; set; }
#endif
        /// <summary>The commitMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitMessage { get; set; }
#nullable restore
#else
        public string CommitMessage { get; set; }
#endif
        /// <summary>The connectedOuterServices property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.IngestionWorkflowService.Models.ConnectedOuterService>? ConnectedOuterServices { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.IngestionWorkflowService.Models.ConnectedOuterService> ConnectedOuterServices { get; set; }
#endif
        /// <summary>The featureFlagStates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.IngestionWorkflowService.Models.FeatureFlagState>? FeatureFlagStates { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.IngestionWorkflowService.Models.FeatureFlagState> FeatureFlagStates { get; set; }
#endif
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.IngestionWorkflowService.Models.VersionInfo"/> and sets the default values.
        /// </summary>
        public VersionInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.IngestionWorkflowService.Models.VersionInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.IngestionWorkflowService.Models.VersionInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.IngestionWorkflowService.Models.VersionInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "artifactId", n => { ArtifactId = n.GetStringValue(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "buildTime", n => { BuildTime = n.GetStringValue(); } },
                { "commitId", n => { CommitId = n.GetStringValue(); } },
                { "commitMessage", n => { CommitMessage = n.GetStringValue(); } },
                { "connectedOuterServices", n => { ConnectedOuterServices = n.GetCollectionOfObjectValues<global::OsduCsharpClient.IngestionWorkflowService.Models.ConnectedOuterService>(global::OsduCsharpClient.IngestionWorkflowService.Models.ConnectedOuterService.CreateFromDiscriminatorValue)?.AsList(); } },
                { "featureFlagStates", n => { FeatureFlagStates = n.GetCollectionOfObjectValues<global::OsduCsharpClient.IngestionWorkflowService.Models.FeatureFlagState>(global::OsduCsharpClient.IngestionWorkflowService.Models.FeatureFlagState.CreateFromDiscriminatorValue)?.AsList(); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("artifactId", ArtifactId);
            writer.WriteStringValue("branch", Branch);
            writer.WriteStringValue("buildTime", BuildTime);
            writer.WriteStringValue("commitId", CommitId);
            writer.WriteStringValue("commitMessage", CommitMessage);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.IngestionWorkflowService.Models.ConnectedOuterService>("connectedOuterServices", ConnectedOuterServices);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.IngestionWorkflowService.Models.FeatureFlagState>("featureFlagStates", FeatureFlagStates);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
