// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OsduCsharpClient.IngestionWorkflowService.Models
{
    /// <summary>Task execution status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowRunResponse_status
    {
        [EnumMember(Value = "INPROGRESS")]
        #pragma warning disable CS1591
        INPROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL_SUCCESS")]
        #pragma warning disable CS1591
        PARTIAL_SUCCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        SUCCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBMITTED")]
        #pragma warning disable CS1591
        SUBMITTED,
        #pragma warning restore CS1591
    }
}
