// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// This is used to store the latest summary of data quality evaluation results for each RuleSet and is associated by reference to a work product component or master data object. Only 1 DataQualitySummary per WPC/Master Object
/// </summary>
public class DataQualitySummary_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-DataQualitySummary:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList100 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags100 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList100? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem100> Meta { get; set; }

    [JsonPropertyName("data")]
    public DataQualitySummary_1_0_0Data? Data { get; set; }

}

public class DataQualitySummary_1_0_0Data : AbstractCommonResources100 // Also composes: AbstractWPCGroupType120, AbstractWorkProductComponent110
{
    /// <summary>
    /// The reference to the evaluated data record. The record version number is required.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("EvaluatedRecordID")]
    public string EvaluatedRecordID { get; set; }

    /// <summary>
    /// The set of Data Quality Review objects associated with the data quality summary
    /// </summary>
    [JsonPropertyName("DataQualitySummarySet")]
    public List<DataQualitySummary_1_0_0DataDataQualitySummarySet> DataQualitySummarySet { get; set; }

    /// <summary>
    /// The EvaluatedRecordID's kind.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:([0-9]+)?(\.)?([0-9]+)?(\.)?([0-9]+)?$")]
    [JsonPropertyName("EvaluatedKind")]
    public string EvaluatedKind { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// This is used to store the latest summary of data quality evaluation results for each RuleSet and is associated by reference to a work product component or master data object. Only one DataQualityReview per DataQualityRuleSet
/// </summary>
public class DataQualitySummary_1_0_0DataDataQualitySummarySet
{
    /// <summary>
    /// The reference to the data quality rule set run for the data quality summary. Unique Key for the item in the DataQualitySummarySet array.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-DataQualityRuleSet:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DataQualityRuleSetID")]
    public string DataQualityRuleSetID { get; set; }

    /// <summary>
    /// The name of the data quality rule set run for the data quality summary which should stay consistent with the DataQualityRuleSet. Denormalized for easier discoverability of the summaries, but needs to be kept up to date.
    /// </summary>
    [JsonPropertyName("DataQualityRuleSetName")]
    public string DataQualityRuleSetName { get; set; }

    /// <summary>
    /// This ID points to a Data Quality object used to store the result from a run of a Data Quality Metric Evaluation engine. Captures summary information, such as which rule-set(s) and rule(s) have been used, when this was run and by whom. Detailed results may be associated with a dataset.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-DataQuality:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DataQualityID")]
    public string DataQualityID { get; set; }

    /// <summary>
    /// The date-time at which the quality assessment started.
    /// </summary>
    [JsonPropertyName("StartDateTime")]
    public DateTimeOffset StartDateTime { get; set; }

    /// <summary>
    /// The reference to the assessment calculation method.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-QualityAssessmentMethod:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("MethodID")]
    public string MethodID { get; set; }

    /// <summary>
    /// The assessment score in % aggregated for all dimension types.
    /// </summary>
    [JsonPropertyName("TotalScore")]
    public double? TotalScore { get; set; }

    /// <summary>
    /// The individual scores per dimension.
    /// </summary>
    [JsonPropertyName("DimensionMetrics")]
    public List<DataQualitySummary_1_0_0DataDataQualitySummarySetDimensionMetrics> DimensionMetrics { get; set; }

}

/// <summary>
/// The assessment score per data rule dimension type and its weight.
/// </summary>
public class DataQualitySummary_1_0_0DataDataQualitySummarySetDimensionMetrics
{
    /// <summary>
    /// The reference to the DataRuleDimensionType, to which score and weight are associated.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-DataRuleDimensionType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DataRuleDimensionTypeID")]
    public string DataRuleDimensionTypeID { get; set; }

    /// <summary>
    /// The assessment score in % aggregated for this dimension type.
    /// </summary>
    [JsonPropertyName("Score")]
    public double? Score { get; set; }

    /// <summary>
    /// The weight factor for this score for the overall score.
    /// </summary>
    [JsonPropertyName("Weight")]
    public double? Weight { get; set; }

}
