// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// A reservoir simulation rock physics model describes the rock compressibility (AKA compaction) of rock, its thermal properties and additional rock physics properties needed for reservoir simulation. It is an input for the task of reservoir simulation (AKA dynamic reservoir modeling). In OSDU, a reservoir simulation rock physics model and a saturation function set are associated to the ReservoirSimulationModel and assigned to the regions defining the rock properties. This rock physics model data object is only intended to support reservoir simulation, not to capture other rock physics data such as acoustic and elastic properties.
/// </summary>
public class ReservoirSimulationRockPhysicsModel_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-ReservoirSimulationRockPhysicsModel:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public ReservoirSimulationRockPhysicsModel_1_0_0Data? Data { get; set; }

}

public class ReservoirSimulationRockPhysicsModel_1_0_0Data : AbstractCommonResources_1_0_1 // Also composes: AbstractWPCGroupType_1_2_0, AbstractWorkProductComponent_1_1_0
{
    /// <summary>
    /// Identifier of the type of compressibility model used for this rock physics model.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CompressibilityModelType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CompressibilityModelTypeID")]
    public string CompressibilityModelTypeID { get; set; }

    /// <summary>
    /// Identifier of the type of thermal model used for this rock physics model. This is used for the thermal simulations.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ThermalModelType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ThermalModelTypeID")]
    public string ThermalModelTypeID { get; set; }

    /// <summary>
    /// This set of attributes represents the context surrounding the processes used in running through model characterization.
    /// </summary>
    [JsonPropertyName("BasisOfModelling")]
    public ReservoirSimulationRockPhysicsModel_1_0_0DataBasisOfModelling? BasisOfModelling { get; set; }

    /// <summary>
    /// This is used, as a form of lineage, to explicitly indicate the model OSDU record from which this model was derived. Only to be used in the case that this model is derived from another.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-ReservoirSimulationRockPhysicsModel:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ParentModelID")]
    public string ParentModelID { get; set; }

    /// <summary>
    /// This represents the date the model generated was published and made available to the consumers or downstream applications..
    /// </summary>
    [JsonPropertyName("DatePublished")]
    public DateTimeOffset DatePublished { get; set; }

    /// <summary>
    /// An array of remarks that provide more context for this data record.
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// This set of attributes represents the context surrounding the processes used in running through model characterization.
/// </summary>
public class ReservoirSimulationRockPhysicsModel_1_0_0DataBasisOfModelling
{
    /// <summary>
    /// Identifiers of the Samples Analysis records from which this model has been derived.
    /// </summary>
    [JsonPropertyName("CompressibilityModelInputSampleAnalysisIDs")]
    public List<string> CompressibilityModelInputSampleAnalysisIDs { get; set; }

    /// <summary>
    /// Identifies the Persisted Collection containing relevant data used to derive this model, except for SamplesAnalysis, which are identified by CompressibilityModelInputSampleAnalysisIDs.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-PersistedCollection:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CompressibilityModelInputDataCollectionID")]
    public string CompressibilityModelInputDataCollectionID { get; set; }

    /// <summary>
    /// Identifiers of the Samples Analysis records from which this model has been derived.
    /// </summary>
    [JsonPropertyName("ThermalModelInputSampleAnalysisIDs")]
    public List<string> ThermalModelInputSampleAnalysisIDs { get; set; }

    /// <summary>
    /// Identifies the Persisted Collection containing relevant data used to derive this model, except for SamplesAnalysis, which are identified by ThermalModelInputSampleAnalysisIDs.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-PersistedCollection:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ThermalModelInputDataCollectionID")]
    public string ThermalModelInputDataCollectionID { get; set; }

    /// <summary>
    /// The software applications used in creating this data. Best practice is to also capture the application version.
    /// </summary>
    [JsonPropertyName("ModellingApplicationsUsed")]
    public List<string> ModellingApplicationsUsed { get; set; }

    /// <summary>
    /// Identifies the subsequent business workflows for which this data is intended to be used.
    /// </summary>
    [JsonPropertyName("IntendedWorkflowUsageIDs")]
    public List<string> IntendedWorkflowUsageIDs { get; set; }

}
