// <auto-generated/>

// This code was generated by the OSDU Client Generator. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// Attributes needed to find and retrieve a delivered report containing rock and/or fluid sample analysis data. Often this report contains more than one data frame of analysis data and/or more than one Analysis Family. Examples of this could include end-of-well reports, well completion reports, regional multi-well studies, or SCAL reports. This report can be decomposed into analysis sets via the SamplesAnalysis work-product-component. In other cases, this report contains part of a dataset which could then be aggregated into a SamplesAnalysis work-product-component.
/// </summary>
public class SamplesAnalysesReport_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-SamplesAnalysesReport:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public SamplesAnalysesReport_1_0_0Data? Data { get; set; }

}

public class SamplesAnalysesReport_1_0_0Data : AbstractCommonResources_1_0_0 // Also composes: AbstractWPCGroupType_1_2_0, AbstractWorkProductComponent_1_1_0
{
    /// <summary>
    /// The kind of document--from a business standpoint, e.g., multi-well study, etc.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-DocumentType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DocumentTypeID")]
    public string DocumentTypeID { get; set; }

    /// <summary>
    /// Number of pages in the document, useful in cases where if it was described in the acquired manifest as opposed to a derived/calculated value
    /// </summary>
    [JsonPropertyName("NumberOfPages")]
    public int? NumberOfPages { get; set; }

    /// <summary>
    /// The sub-title of the document.
    /// </summary>
    [JsonPropertyName("SubTitle")]
    public string SubTitle { get; set; }

    /// <summary>
    /// A description text or an array of subjects covered by the document. If present this information must compliment the Tag and SubTitle
    /// </summary>
    [JsonPropertyName("DocumentSubject")]
    public string DocumentSubject { get; set; }

    /// <summary>
    /// The date and time that the results of the analysis containing observed measurements or calculations was published
    /// </summary>
    [JsonPropertyName("DatePublished")]
    public DateTimeOffset DatePublished { get; set; }

    /// <summary>
    /// The date and time that the document was last modified
    /// </summary>
    [JsonPropertyName("DateModified")]
    public DateTimeOffset DateModified { get; set; }

    /// <summary>
    /// Document language as listed in the ISO 639-3 https://en.wikipedia.org/wiki/ISO_639, https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes
    /// </summary>
    [JsonPropertyName("DocumentLanguage")]
    public string DocumentLanguage { get; set; }

    /// <summary>
    /// OSDU Record IDs for the Rock and/or Fluid Sample or Samples on which this batch or batches of analysis were performed.
    /// </summary>
    [JsonPropertyName("SampleIDs")]
    public List<string> SampleIDs { get; set; }

    /// <summary>
    /// The names or identifiers of the analyzed samples in this report or document. These names or identifiers are often assigned by the laboratory. This list can be used to assist in locating the appropriate OSDU Sample records or to find the dataset in the parent report.
    /// </summary>
    [JsonPropertyName("ReportSampleIdentifiers")]
    public List<string> ReportSampleIdentifiers { get; set; }

    /// <summary>
    /// A list of all sample analysis types represented by this report, whether the sample analysis type relates to Rock, Fluid, or both.
    /// </summary>
    [JsonPropertyName("SampleAnalysisTypeIDs")]
    public List<string> SampleAnalysisTypeIDs { get; set; }

    /// <summary>
    /// List of higher level grouping terms that are often used within organisations to search for analysis types in addition to the formal Family and Method properties, but which are variable across organisations and therefore do not need to be governed strictly by the OSDU Forum. For example: SCAL, Static SCAL, Dynamic SCAL, Source Rock Analysis. We suggest you use a namespace, like the operators name, like “Shell.SCAL”. BP.SCAL, Equinor.SCAL, Chevron.SCAL, Exxon.SCAL.....
    /// </summary>
    [JsonPropertyName("SamplesAnalysisCategoryTagIDs")]
    public List<string> SamplesAnalysisCategoryTagIDs { get; set; }

    /// <summary>
    /// An array containing operational or quality comments pertaining to the sample analysis represented by this work product component.
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

    /// <summary>
    /// OSDU Record IDs for the laboratories used to conduct the sample analyses contained in this report. This could represent the laboratory company or the laboratory branch.
    /// </summary>
    [JsonPropertyName("LaboratoryIDs")]
    public List<string> LaboratoryIDs { get; set; }

    /// <summary>
    /// List of names of laboratories used to conduct the sample analyses contained in this report. This attribute is more freeform than Laboratory IDs and does not have relationships to OSDU Record IDs. This attribute exists to help with a low bar of ingestion but best practice is to resolve each of these to an OSDU Record ID in the LaboratoryIDs attribute.
    /// </summary>
    [JsonPropertyName("LaboratoryNames")]
    public List<string> LaboratoryNames { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}
