// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// A logical dataset containing seismic traces. The traces are the original recordings, prior to processing.
/// </summary>
public class SeismicFieldTraceData_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-SeismicFieldTraceData:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public SeismicFieldTraceData_1_0_0_Data? Data { get; set; }

}

public class SeismicFieldTraceData_1_0_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractWPCGroupType_1_1_0, AbstractWorkProductComponent_1_1_0
{
    [JsonPropertyName("LiveTraceOutline")]
    public AbstractSpatialLocation_1_1_0? LiveTraceOutline { get; set; }

    /// <summary>
    /// Coordinate reference system of positions in trace header, which matches what is described in BinGrid but is repeated here for convenience and in case bin grid is not defined.  In case of conflict with Bin Grid, this value applies to the coordinates as written into CMPX, CMPY headers. Nevertheless, Bin Grid should be used for mapping purposes.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("HorizontalCRSID")]
    public string HorizontalCRSID { get; set; }

    /// <summary>
    /// For most datasets, the acquisition project that generated the underlying field data.  For merges, probably absent (see processing project for set of acquisition projects used in processing this dataset).
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-SeismicAcquisitionSurvey:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PrincipalAcquisitionProjectID")]
    public string PrincipalAcquisitionProjectID { get; set; }

    /// <summary>
    /// The dimensionality of trace data sets (not as acquired but as in the dataset), such as 2D, 3D, 4D.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicTraceDataDimensionalityType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicTraceDataDimensionalityTypeID")]
    public string SeismicTraceDataDimensionalityTypeID { get; set; }

    /// <summary>
    /// ID of the nature of the vertical axis in the trace data set, usually Depth or Time.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicDomainType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicDomainTypeID")]
    public string SeismicDomainTypeID { get; set; }

    /// <summary>
    /// 2D line name or survey name for the 2D group
    /// </summary>
    [JsonPropertyName("Seismic2DName")]
    public string Seismic2DName { get; set; }

    /// <summary>
    /// ID of the Seismic Trace Data Type
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicAttributeType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicAttributeTypeID")]
    public string SeismicAttributeTypeID { get; set; }

    /// <summary>
    /// ID of the Seismic Filtering Type
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicFilteringType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicFilteringTypeID")]
    public string SeismicFilteringTypeID { get; set; }

    /// <summary>
    /// Reference to the reference-data--SeismicPhase value describing the wavelet phase as estimated/processed for this SeismicTraceData instance.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicPhase:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicPhaseID")]
    public string SeismicPhaseID { get; set; }

    /// <summary>
    /// Reflection polarity of embedded wavelet.  Normal, Reverse, Plus 90, Minus 90 according to SEG standard.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicPolarity:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicPolarityID")]
    public string SeismicPolarityID { get; set; }

    /// <summary>
    /// Vertical sampling interval of data.
    /// </summary>
    [JsonPropertyName("SampleInterval")]
    public double? SampleInterval { get; set; }

    /// <summary>
    /// Number of samples in the vertical direction.
    /// </summary>
    [JsonPropertyName("SampleCount")]
    public int? SampleCount { get; set; }

    /// <summary>
    /// Indicates if the volume is a product of the difference between 4D surveys
    /// </summary>
    [JsonPropertyName("Difference")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? Difference { get; set; }

    /// <summary>
    /// The sample axis value in the vertical dimension at which Time formatted data starts. Use SeismicDomainType to know which of time or depth pairs is the actual range vs. what is estimated.
    /// </summary>
    [JsonPropertyName("StartTime")]
    public double? StartTime { get; set; }

    /// <summary>
    /// The sample axis value in the vertical dimension at which Time formatted data starts. Use SeismicDomainType to know which of time or depth pairs is the actual range vs. what is estimated.
    /// </summary>
    [JsonPropertyName("EndTime")]
    public double? EndTime { get; set; }

    /// <summary>
    /// The sample axis value in the vertical dimension at which Depth formatted data starts. Use SeismicDomainType to know which of time or depth pairs is the actual range vs. what is estimated.
    /// </summary>
    [JsonPropertyName("StartDepth")]
    public double? StartDepth { get; set; }

    /// <summary>
    /// The sample axis value in the vertical dimension at which Depth formatted data ends. Use SeismicDomainType to know which of time or depth pairs is the actual range vs. what is estimated.
    /// </summary>
    [JsonPropertyName("EndDepth")]
    public double? EndDepth { get; set; }

    /// <summary>
    /// How many traces are in the volume
    /// </summary>
    [JsonPropertyName("TraceCount")]
    public int? TraceCount { get; set; }

    /// <summary>
    /// Maximum trace length calculated using depth or time start and end points as appropriate according to SeismicDomainType.
    /// </summary>
    [JsonPropertyName("TraceLength")]
    public double? TraceLength { get; set; }

    /// <summary>
    /// UOM for vertical trace domain values
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("TraceDomainUOM")]
    public string TraceDomainUOM { get; set; }

    /// <summary>
    /// The shotpoint that came before all others
    /// </summary>
    [JsonPropertyName("FirstShotPoint")]
    public double? FirstShotPoint { get; set; }

    /// <summary>
    /// The last shotpoint represented by the data
    /// </summary>
    [JsonPropertyName("LastShotPoint")]
    public double? LastShotPoint { get; set; }

    /// <summary>
    /// Datum value, the elevation of zero time/depth on the vertical axis in the domain of SeismicDomainType relative to the vertical reference datum used (usually MSL). Positive is upward from zero elevation to seismic datum).
    /// </summary>
    [JsonPropertyName("VerticalDatumOffset")]
    public double? VerticalDatumOffset { get; set; }

    /// <summary>
    /// Identifies a vertical reference datum type. E.g. mean sea level, ground level, mudline.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-VerticalMeasurementType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalMeasurementTypeID")]
    public string VerticalMeasurementTypeID { get; set; }

    /// <summary>
    /// Indicates how much the data has been shifted from the Vertical Datum (seismic reference datum) in the domain and units of SeismicDomainType and in the sense that a positive number causes a sample to move downward in physical space (lower elevation).
    /// </summary>
    [JsonPropertyName("ShiftApplied")]
    public double? ShiftApplied { get; set; }

    /// <summary>
    /// Sample data format in terms of sample value precision 8bit Integer, 16bit Floating Point etc.
    /// </summary>
    [JsonPropertyName("Precision")]
    public SeismicFieldTraceData_1_0_0_Data_Precision? Precision { get; set; }

    /// <summary>
    /// Processing Parameters to simply capture process history until full provenance model can be implemented.
    /// </summary>
    [JsonPropertyName("ProcessingParameters")]
    public List<SeismicFieldTraceData_1_0_0_Data_ProcessingParameters> ProcessingParameters { get; set; }

    /// <summary>
    /// Character metadata from headers inside file, such as the EBCDIC header of SEGD.  This is an array to capture each stanza separately.
    /// </summary>
    [JsonPropertyName("TextualFileHeader")]
    public List<string> TextualFileHeader { get; set; }

    /// <summary>
    /// The actual maximum amplitude value found in the dataset.
    /// </summary>
    [JsonPropertyName("RangeAmplitudeMax")]
    public double? RangeAmplitudeMax { get; set; }

    /// <summary>
    /// The actual minimum amplitude value found in the dataset.
    /// </summary>
    [JsonPropertyName("RangeAmplitudeMin")]
    public double? RangeAmplitudeMin { get; set; }

    /// <summary>
    /// The observed wave mode type in this trace data set (P, Sv, etc).
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicWaveType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicWaveTypeID")]
    public string SeismicWaveTypeID { get; set; }

    /// <summary>
    /// Defines the sorting order of the trace data as stored in the file(s).
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicTraceSortOrder:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SortOrderID")]
    public string SortOrderID { get; set; }

    /// <summary>
    /// The type of gathers in this dataset.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicGatherType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("GatherTypeID")]
    public string GatherTypeID { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// Sample data format in terms of sample value precision 8bit Integer, 16bit Floating Point etc.
/// </summary>
public class SeismicFieldTraceData_1_0_0_Data_Precision
{
    /// <summary>
    /// SRN of a reference value for binary data types, such as INT, UINT, FLOAT, IBM_FLOAT, ASCII, EBCDIC.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-WordFormatType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WordFormat")]
    public string WordFormat { get; set; }

    /// <summary>
    /// Size of the word in bytes.
    /// </summary>
    [JsonPropertyName("WordWidth")]
    public int? WordWidth { get; set; }

}

/// <summary>
/// Processing Parameters to simply capture process history until full provenance model can be implemented.
/// </summary>
public class SeismicFieldTraceData_1_0_0_Data_ProcessingParameters
{
    /// <summary>
    /// Processing Parameter Type
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ProcessingParameterType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ProcessingParameterTypeID")]
    public string ProcessingParameterTypeID { get; set; }

    /// <summary>
    /// The quantity for the processing parameter. May include units, ordering, and other descriptions.
    /// </summary>
    [JsonPropertyName("ProcessingParameterValue")]
    public string ProcessingParameterValue { get; set; }

}
