// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// A representation of a single fault picked on the basis of seismic data. The record carries information about the seismic geometry context. It can be part of an UnsealedSurfaceFramework.
/// </summary>
public class SeismicFault_1_2_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-SeismicFault:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public SeismicFault_1_2_0Data? Data { get; set; }

}

public class SeismicFault_1_2_0Data : AbstractCommonResources_1_0_0 // Also composes: AbstractWPCGroupType_1_2_0, AbstractWorkProductComponent_1_1_0, AbstractRepresentation_1_0_0
{
    /// <summary>
    /// Method used to pick faults. E.g.Autotracked, Grid, Manual Picked
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicPickingType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicPickingTypeID")]
    public string SeismicPickingTypeID { get; set; }

    /// <summary>
    /// Optional comment to capture interpreter thoughts.  Distinguished from Description which is a general explanation of the object.
    /// </summary>
    [JsonPropertyName("Remark")]
    public string Remark { get; set; }

    /// <summary>
    /// Seismic Volumes picked against
    /// </summary>
    [JsonPropertyName("SeismicTraceDataIDs")]
    public List<string> SeismicTraceDataIDs { get; set; }

    /// <summary>
    /// Vertical domain of faults.  E.g. Time, Depth
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicDomainType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicDomainTypeID")]
    public string SeismicDomainTypeID { get; set; }

    /// <summary>
    /// the Bin Grid of the Fault System when coordinates are specified in seismic bin inline/crossline.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-SeismicBinGrid:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("BinGridID")]
    public string BinGridID { get; set; }

    /// <summary>
    /// The list of explicit 2D seismic line geometries overriding any definitions inferred from Seismic2DInterpretationSet. If empty and Seismic2DInterpretationSetID is populated, Seismic2DInterpretationSet.SeismicLineGeometries[].SeismicLineGeometryID apply.
    /// </summary>
    [JsonPropertyName("SeismicLineGeometryIDs")]
    public List<string> SeismicLineGeometryIDs { get; set; }

    /// <summary>
    /// Datum value, the elevation of zero time/depth on the vertical axis in the domain of seismicdomaintype relative to the vertical reference datum used (usually MSL). Positive is upward from zero elevation to seismic datum).
    /// </summary>
    [JsonPropertyName("VerticalDatumOffset")]
    public double? VerticalDatumOffset { get; set; }

    /// <summary>
    /// Identifies a vertical reference datum type. E.g. mean sea level, ground level, mudline.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-VerticalMeasurementType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalMeasurementTypeID")]
    public string VerticalMeasurementTypeID { get; set; }

    /// <summary>
    /// Value used to produce vertical static shifts in data.
    /// </summary>
    [JsonPropertyName("ReplacementVelocity")]
    public double? ReplacementVelocity { get; set; }

    /// <summary>
    /// Geological type of fault geometry. E.g. Thrust (thr), Reverse (rev), Normal(norm)
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SeismicFaultType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("SeismicFaultTypeID")]
    public string SeismicFaultTypeID { get; set; }

    /// <summary>
    /// Maximum linear dimension measured along strike of the slip surface
    /// </summary>
    [JsonPropertyName("SeismicFaultLength")]
    public double? SeismicFaultLength { get; set; }

    /// <summary>
    /// Surface Area of the Fault Plane
    /// </summary>
    [JsonPropertyName("SeismicFaultSurfaceArea")]
    public double? SeismicFaultSurfaceArea { get; set; }

    /// <summary>
    /// Maximum vertical angle of fault
    /// </summary>
    [JsonPropertyName("VerticalFaultDipAngle")]
    public double? VerticalFaultDipAngle { get; set; }

    /// <summary>
    /// Maximum stratigraphic heave, the apparent horizontal component of the net-slip.
    /// </summary>
    [JsonPropertyName("FaultHeaveNumber")]
    public double? FaultHeaveNumber { get; set; }

    /// <summary>
    /// Net (average) Slip.
    /// </summary>
    [JsonPropertyName("FaultNetSlipNumber")]
    public double? FaultNetSlipNumber { get; set; }

    /// <summary>
    /// Maximum vertical offset of faulted strata.
    /// </summary>
    [JsonPropertyName("StratigraphicFaultOffset")]
    public double? StratigraphicFaultOffset { get; set; }

    /// <summary>
    /// The person or team who interpreted the fault data.
    /// </summary>
    [JsonPropertyName("Interpreter")]
    public string Interpreter { get; set; }

    /// <summary>
    /// The RepresentationRole assigned to this SeismicFault. Examples: FaultSticks, Pick, FaultCenterLine.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-RepresentationRole:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("Role")]
    public string Role { get; set; }

    /// <summary>
    /// The FaultSystem RepresentationType assigned to this SeismicFault. Examples: PolylineSet, TriangulatedSurface.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-RepresentationType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("Type")]
    public string Type { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}
