// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// Wellbore Markers identify the depth in a wellbore, measured below a reference elevation, at which a person or an automated process identifies a noteworthy observation, which is usually a change in the rock that intersects that wellbore. Formation Marker data includes attributes/properties that put these depths in context. Formation Markers are sometimes known as picks or formation tops.
/// </summary>
public class WellboreMarkerSet_1_3_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellboreMarkerSet:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public WellboreMarkerSet_1_3_0_Data? Data { get; set; }

}

public class WellboreMarkerSet_1_3_0_Data : AbstractCommonResources_1_0_0 // Also composes: AbstractWPCGroupType_1_1_0, AbstractWorkProductComponent_1_1_0
{
    /// <summary>
    /// The record id, which identifies this OSDU File or dataset resource.
    /// </summary>
    [JsonPropertyName("Datasets")]
    public List<string> Datasets { get; set; }

    /// <summary>
    /// An array of references to content in Domain Data Management Services represented by this work-product-component. The references are formed as URI following https://www.rfc-editor.org/rfc/rfc3986#page-16. This property is exclusively populated by DDMSs. If a work-product-component is represented in more than one DDMS, DDMSs are obliged to find the specific reference by inspecting the URI's authority values matching the DDMS id.
    /// </summary>
    [JsonPropertyName("DDMSDatasets")]
    public List<string> DDMSDatasets { get; set; }

    /// <summary>
    /// An array of Artefacts - each artefact has a Role, Resource tuple. An artefact is distinct from the file, in the sense certain valuable information is generated during loading process (Artefact generation process). Examples include retrieving location data, performing an OCR which may result in the generation of artefacts which need to be preserved distinctly
    /// </summary>
    [JsonPropertyName("Artefacts")]
    public List<WellboreMarkerSet_1_3_0_Data_Artefacts> Artefacts { get; set; }

    /// <summary>
    /// A flag that indicates if the work product component is undergoing an extended load.  It reflects the fact that the work product component is in an early stage and may be updated before finalization.
    /// </summary>
    [JsonPropertyName("IsExtendedLoad")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsExtendedLoad { get; set; }

    /// <summary>
    /// A flag that indicates if the work product component is searchable, which means covered in the search index.
    /// </summary>
    [JsonPropertyName("IsDiscoverable")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsDiscoverable { get; set; }

    /// <summary>
    /// Describes a record's overall suitability for general business consumption based on data quality. Clarifications: Since Certified is the highest classification of suitable quality, any further change or versioning of a Certified record should be carefully considered and justified. If a Technical Assurance value is not populated then one can assume the data has not been evaluated or its quality is unknown (=Unevaluated). Technical Assurance values are not intended to be used for the identification of a single "preferred" or "definitive" record by comparison with other records.
    /// </summary>
    [JsonPropertyName("TechnicalAssurances")]
    public List<AbstractTechnicalAssurance_1_1_0> TechnicalAssurances { get; set; }

    /// <summary>
    /// Alternative names, including historical, by which this work-product-component is/has been known (it should include all the identifiers).
    /// </summary>
    [JsonPropertyName("NameAliases")]
    public List<AbstractAliasNames_1_0_0> NameAliases { get; set; }

    /// <summary>
    /// Name
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

    /// <summary>
    /// Description.  Summary of the work product component.  Not the same as Remark which captures thoughts of creator about the wpc.
    /// </summary>
    [JsonPropertyName("Description")]
    public string Description { get; set; }

    /// <summary>
    /// Date that a resource (work  product component here) is formed outside of OSDU before loading (e.g. publication date).
    /// </summary>
    [JsonPropertyName("CreationDateTime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? CreationDateTime { get; set; }

    /// <summary>
    /// Array of key words to identify the work product, especially to help in search.
    /// </summary>
    [JsonPropertyName("Tags")]
    public List<string> Tags { get; set; }

    [JsonPropertyName("SpatialPoint")]
    public AbstractSpatialLocation_1_1_0? SpatialPoint { get; set; }

    [JsonPropertyName("SpatialArea")]
    public AbstractSpatialLocation_1_1_0? SpatialArea { get; set; }

    /// <summary>
    /// List of geographic entities which provide context to the WPC.  This may include multiple types or multiple values of the same type.
    /// </summary>
    [JsonPropertyName("GeoContexts")]
    public List<AbstractGeoContext_1_0_0> GeoContexts { get; set; }

    /// <summary>
    /// Name of the person that first submitted the work product component to OSDU.
    /// </summary>
    [JsonPropertyName("SubmitterName")]
    public string SubmitterName { get; set; }

    /// <summary>
    /// Array of business processes/workflows that the work product component has been through (ex. well planning, exploration).
    /// </summary>
    [JsonPropertyName("BusinessActivities")]
    public List<string> BusinessActivities { get; set; }

    /// <summary>
    /// Array of Authors' names of the work product component.  Could be a person or company entity.
    /// </summary>
    [JsonPropertyName("AuthorIDs")]
    public List<string> AuthorIDs { get; set; }

    /// <summary>
    /// Defines relationships with other objects (any kind of Resource) upon which this work product component depends.  The assertion is directed only from the asserting WPC to ancestor objects, not children.  It should not be used to refer to files or artefacts within the WPC -- the association within the WPC is sufficient and Artefacts are actually children of the main WPC file. They should be recorded in the data.Artefacts[] array.
    /// </summary>
    [JsonPropertyName("LineageAssertions")]
    public List<WellboreMarkerSet_1_3_0_Data_LineageAssertions> LineageAssertions { get; set; }

    /// <summary>
    /// The Wellbore ID, to which the markers in this set belong.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreID")]
    public string WellboreID { get; set; }

    [JsonPropertyName("VerticalMeasurement")]
    public AbstractFacilityVerticalMeasurement_1_0_0? VerticalMeasurement { get; set; }

    /// <summary>
    /// The array of MarkerProperty definitions describing the available properties for this instance of WellboreMarkerSet.
    /// </summary>
    [JsonPropertyName("AvailableMarkerProperties")]
    public List<WellboreMarkerSet_1_3_0_Data_AvailableMarkerProperties> AvailableMarkerProperties { get; set; }

    /// <summary>
    /// The array of marker meta data in this set. Markers are externally identified by data.Markers[].MarkerID, ideally a UUID. Older versions of the WellboreMarkerSet schema do not have this identifier. In this case, the string-converted array index is used as MarkerID. The the first index is "0".
    /// </summary>
    [JsonPropertyName("Markers")]
    public List<WellboreMarkerSet_1_3_0_Data_Markers> Markers { get; set; }

    /// <summary>
    /// The optional reference to a stratigraphic column (referring to multiple StratigraphicColumnRankInterpretation) providing the stratigraphic framework for the WellboreMarkerSet. It demonstrates the intent to describe complex, potentially overlapping stratigraphic intervals. Only one of the properties StratigraphicColumnID or StratigraphicColumnRankInterpretationID should be populated.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-StratigraphicColumn:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("StratigraphicColumnID")]
    public string StratigraphicColumnID { get; set; }

    /// <summary>
    /// The optional reference to a StratigraphicColumnRankInterpretation. It expresses the intent of a stratigraphic framework with non-overlapping intervals. Only one of the properties StratigraphicColumnID or StratigraphicColumnRankInterpretationID should be populated.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-StratigraphicColumnRankInterpretation:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("StratigraphicColumnRankInterpretationID")]
    public string StratigraphicColumnRankInterpretationID { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// An array of Artefacts - each artefact has a Role, Resource tuple. An artefact is distinct from the file, in the sense certain valuable information is generated during loading process (Artefact generation process). Examples include retrieving location data, performing an OCR which may result in the generation of artefacts which need to be preserved distinctly
/// </summary>
public class WellboreMarkerSet_1_3_0_Data_Artefacts
{
    /// <summary>
    /// The record id of this artefact's role.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-ArtefactRole:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("RoleID")]
    public string RoleID { get; set; }

    /// <summary>
    /// The kind or schema ID of the artefact. Resolvable with the Schema Service.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("ResourceKind")]
    public string ResourceKind { get; set; }

    /// <summary>
    /// The SRN which identifies this OSDU Artefact resource.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:dataset\-\-[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ResourceID")]
    public string ResourceID { get; set; }

}

/// <summary>
/// Defines relationships with other objects (any kind of Resource) upon which this work product component depends.  The assertion is directed only from the asserting WPC to ancestor objects, not children.  It should not be used to refer to files or artefacts within the WPC -- the association within the WPC is sufficient and Artefacts are actually children of the main WPC file. They should be recorded in the data.Artefacts[] array.
/// </summary>
public class WellboreMarkerSet_1_3_0_Data_LineageAssertions
{
    /// <summary>
    /// The object reference identifying the DIRECT, INDIRECT, REFERENCE dependency.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ID")]
    public string ID { get; set; }

    /// <summary>
    /// Used by LineageAssertion to describe the nature of the line of descent of a work product component from a prior Resource, such as DIRECT, INDIRECT, REFERENCE.  It is not for proximity (number of nodes away), it is not to cover all the relationships in a full ontology or graph, and it is not to describe the type of activity that created the asserting WPC.  LineageAssertion does not encompass a full provenance, process history, or activity model.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-LineageRelationshipType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("LineageRelationshipType")]
    public string LineageRelationshipType { get; set; }

}

/// <summary>
/// A set of properties describing a marker property which is available for this instance of a WellboreMarkerSet.
/// </summary>
public class WellboreMarkerSet_1_3_0_Data_AvailableMarkerProperties
{
    /// <summary>
    /// The reference to a marker property type - or if interpreted as CSV columns, the 'well-known column type. It is a relationship to a reference-data--MarkerPropertyType record id.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-MarkerPropertyType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("MarkerPropertyTypeID")]
    public string MarkerPropertyTypeID { get; set; }

    /// <summary>
    /// Unit of Measure for the marker properties of type MarkerPropertyType.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("MarkerPropertyUnitID")]
    public string MarkerPropertyUnitID { get; set; }

    /// <summary>
    /// The name of the marker property (e.g. column in a CSV document) as originally found. If absent The name of the MarkerPropertyType is intended to be used.
    /// </summary>
    [JsonPropertyName("Name")]
    public string Name { get; set; }

}

/// <summary>
/// The array of marker meta data in this set.
/// </summary>
public class WellboreMarkerSet_1_3_0_Data_Markers
{
    /// <summary>
    /// Name of the Marker
    /// </summary>
    [JsonPropertyName("MarkerName")]
    public string MarkerName { get; set; }

    /// <summary>
    /// A unique identifier of the marker in the list of data.Markers[], ideally a UUID. If unpopulated, the string-converted element index number is used. The first index is "0".
    /// </summary>
    [JsonPropertyName("MarkerID")]
    public string MarkerID { get; set; }

    /// <summary>
    /// The optional relationship to a HorizonInterpretation, GeobodyBoundaryInterpretation or FaultInterpretation.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:(work-product-component\-\-HorizonInterpretation|work-product-component\-\-FaultInterpretation|work-product-component\-\-GeobodyBoundaryInterpretation):[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("InterpretationID")]
    public string InterpretationID { get; set; }

    /// <summary>
    /// The depth at which the Marker was noted.
    /// </summary>
    [JsonPropertyName("MarkerMeasuredDepth")]
    public double? MarkerMeasuredDepth { get; set; }

    /// <summary>
    /// The Marker's TVD converted to a Sub-Sea Vertical depth, i.e., below Mean Sea Level. Note that TVD values above MSL are negative. This is the same as true vertical depth referenced to the vertical CRS “MSL depth”.
    /// </summary>
    [JsonPropertyName("MarkerSubSeaVerticalDepth")]
    public double? MarkerSubSeaVerticalDepth { get; set; }

    /// <summary>
    /// Timestamp of the date and time when the when the Marker was interpreted.
    /// </summary>
    [JsonPropertyName("MarkerDate")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public DateTimeOffset? MarkerDate { get; set; }

    /// <summary>
    /// Any observation number that distinguishes a Marker observation from others with same Marker name, date.
    /// </summary>
    [JsonPropertyName("MarkerObservationNumber")]
    public double? MarkerObservationNumber { get; set; }

    /// <summary>
    /// The name of the Marker interpreter (could be a person or vendor).
    /// </summary>
    [JsonPropertyName("MarkerInterpreter")]
    public string MarkerInterpreter { get; set; }

    /// <summary>
    /// Marker Type Reference Type. Possible values - Biostratigraphy, Lithostratigraphy, seismic, depth of well, sequence, flow unit
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-MarkerType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("MarkerTypeID")]
    public string MarkerTypeID { get; set; }

    /// <summary>
    /// Feature Type Reference Type. Possible values - Base, top, fault, salt, reef, sea floor
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-FeatureType:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("FeatureTypeID")]
    public string FeatureTypeID { get; set; }

    /// <summary>
    /// Name of the feature the marker is characterizing
    /// </summary>
    [JsonPropertyName("FeatureName")]
    public string FeatureName { get; set; }

    /// <summary>
    /// The distance vertically above the Marker position that marks the limit of the high confidence range for the Marker pick.
    /// </summary>
    [JsonPropertyName("PositiveVerticalDelta")]
    public double? PositiveVerticalDelta { get; set; }

    /// <summary>
    /// The distance vertically below the Marker position that marks the limit of the high confidence range for the Marker pick.
    /// </summary>
    [JsonPropertyName("NegativeVerticalDelta")]
    public double? NegativeVerticalDelta { get; set; }

    /// <summary>
    /// Dip angle for the Wellbore Marker.
    /// </summary>
    [JsonPropertyName("SurfaceDipAngle")]
    public double? SurfaceDipAngle { get; set; }

    /// <summary>
    /// Dip azimuth for the Wellbore Marker.
    /// </summary>
    [JsonPropertyName("SurfaceDipAzimuth")]
    public double? SurfaceDipAzimuth { get; set; }

    /// <summary>
    /// The geologic reason why a portion of material (typically a rock formation) is missing from the real world material/rock being measured, compared to what was expected based on offset wells. Examples: fault, unconformity, fold. This property corresponds to marker property type reference-data--MarkerPropertyType:MissingReason.
    /// </summary>
    [JsonPropertyName("Missing")]
    public string Missing { get; set; }

    /// <summary>
    /// Associated geological age
    /// </summary>
    [JsonPropertyName("GeologicalAge")]
    public string GeologicalAge { get; set; }

}
