// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;
using Osdu.Client.Schemas.Abstract;

namespace Osdu.Client.Schemas.WorkProductComponent;

/// <summary>
/// Entity aiming to capture the results of interpretations carried out on the results of a well test activity. Intended to be partnered with a WellPressureTestRawMeasurement WPC that captures raw measurements before any kind of processing, composing, interpretation or analysis
/// </summary>
public class WellPressureTestInterpretation_1_0_0
{
    /// <summary>
    /// Previously called ResourceID or SRN which identifies this OSDU resource object without version.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellPressureTestInterpretation:[\w\-\.\:\%]+$")]
    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>
    /// The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$")]
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary>
    /// The version number of this OSDU resource; set by the framework.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }

    [Required]
    [JsonPropertyName("acl")]
    public AbstractAccessControlList_1_0_0 Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public AbstractLegalTags_1_0_0 Legal { get; set; }

    /// <summary>
    /// A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("createTime")]
    public DateTimeOffset CreateTime { get; set; }

    /// <summary>
    /// The user reference, which created the first version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("createUser")]
    public string CreateUser { get; set; }

    /// <summary>
    /// Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.
    /// </summary>
    [JsonPropertyName("modifyTime")]
    public DateTimeOffset ModifyTime { get; set; }

    /// <summary>
    /// The user reference, which created this version of this resource object. Set by the System.
    /// </summary>
    [JsonPropertyName("modifyUser")]
    public string ModifyUser { get; set; }

    [JsonPropertyName("ancestry")]
    public AbstractLegalParentList_1_0_0? Ancestry { get; set; }

    /// <summary>
    /// The Frame of Reference meta data section linking the named properties to self-contained definitions.
    /// </summary>
    [JsonPropertyName("meta")]
    public List<AbstractMetaItem_1_0_0> Meta { get; set; }

    [JsonPropertyName("data")]
    public WellPressureTestInterpretation_1_0_0Data? Data { get; set; }

}

public class WellPressureTestInterpretation_1_0_0Data : AbstractCommonResources_1_0_1 // Also composes: AbstractWPCGroupType_1_2_0, AbstractWorkProductComponent_1_1_0
{
    /// <summary>
    /// Identifier of the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellPressureTestRawMeasurement:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellPressureTestRawMeasurementID")]
    public string WellPressureTestRawMeasurementID { get; set; }

    /// <summary>
    /// Optional Identifier of the Test Number that is most representative of the overall interpretation within the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [JsonPropertyName("WellPressureTestRawMeasurementTestIdentifier")]
    public int? WellPressureTestRawMeasurementTestIdentifier { get; set; }

    /// <summary>
    /// Optional Identifier of the Test Measurement Period Number that is most representative of the overall interpretation within the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [JsonPropertyName("WellPressureTestRawMeasurementTestPeriodIdentifier")]
    public int? WellPressureTestRawMeasurementTestPeriodIdentifier { get; set; }

    /// <summary>
    /// The date (and time) on which the interpretation was performed
    /// </summary>
    [JsonPropertyName("PressureTestInterpretationDateTime")]
    public DateTimeOffset PressureTestInterpretationDateTime { get; set; }

    /// <summary>
    /// The subjective quality classification of the analysis (interpretation) and its conclusions. E.g. Excellent, Good, Poor etc. A Confidence classification could also be used here if there is an issue with the certainty of the interpretation.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SubjectiveClassificationRating:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("InterpretationSubjectiveClassificationRatingID")]
    public string InterpretationSubjectiveClassificationRatingID { get; set; }

    /// <summary>
    /// Boolean indicating where this Interpretation is the preferred record where multiple interpretations may have been performed over time e.g. re-interpretation
    /// </summary>
    [JsonPropertyName("IsPreferred")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsPreferred { get; set; }

    /// <summary>
    /// The details of the individual(s) responsible for performing the interpretation activity
    /// </summary>
    [JsonPropertyName("InterpretationAnalysts")]
    public List<AbstractContact_1_1_0> InterpretationAnalysts { get; set; }

    /// <summary>
    /// Time stamped remarks associated with the interpretation activity
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

    /// <summary>
    /// Array of detailed results of the interpretation activity
    /// </summary>
    [JsonPropertyName("InterpretationResults")]
    public List<WellPressureTestInterpretation_1_0_0DataInterpretationResults> InterpretationResults { get; set; }

    [JsonPropertyName("InterpretationResultProperties")]
    public AbstractColumnBasedTable_1_2_0? InterpretationResultProperties { get; set; }

    [JsonPropertyName("ExtensionProperties")]
    public object? ExtensionProperties { get; set; }

}

/// <summary>
/// Contains the reservoir specific results of interpretations carried out on the results of well tests. Also contains the parameter values needed to calculate the pressure at reservoir datum.
/// </summary>
public class WellPressureTestInterpretation_1_0_0DataInterpretationResults
{
    /// <summary>
    /// The unique number of the result array member in the data.InterpretationResults[] array.
    /// </summary>
    [JsonPropertyName("WellPressureTestInterpretationNumber")]
    public int? WellPressureTestInterpretationNumber { get; set; }

    /// <summary>
    /// Optional Identifier of the Station Number that is most closely associated with this result within the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [JsonPropertyName("WellPressureTestAcquisitionStationIdentifier")]
    public int? WellPressureTestAcquisitionStationIdentifier { get; set; }

    /// <summary>
    /// Optional Identifier of the Test Number that is most closely associated with this interpretation array element within the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [JsonPropertyName("WellPressureTestRawMeasurementTestIdentifier")]
    public int? WellPressureTestRawMeasurementTestIdentifier { get; set; }

    /// <summary>
    /// Optional Identifier of the Test Period Number that is most closely associated with this interpretation array element within the related Well Pressure Test Raw Measurement Work Product Component
    /// </summary>
    [JsonPropertyName("WellPressureTestRawMeasurementTestPeriodIdentifier")]
    public int? WellPressureTestRawMeasurementTestPeriodIdentifier { get; set; }

    /// <summary>
    /// Boolean indicating where this Interpretation result is the preferred where multiple interpretation results are present
    /// </summary>
    [JsonPropertyName("IsPreferred")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? IsPreferred { get; set; }

    /// <summary>
    /// Segment that contains important reference elements used to support the interpretation activity
    /// </summary>
    [JsonPropertyName("InterpretationInput")]
    public WellPressureTestInterpretation_1_0_0DataInterpretationResultsInterpretationInput? InterpretationInput { get; set; }

    /// <summary>
    /// Identifier linking to the dominant parent reservoir entity (It could be either a Reservoir or ReservoirSegment). This is the entity whose characteristics such as Reservoir Pressure are interpreted
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:(master-data\-\-Reservoir|master-data\-\-ReservoirSegment):[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("DominantReservoirEntityID")]
    public string DominantReservoirEntityID { get; set; }

    /// <summary>
    /// Array of optional commingled Reservoirs or Reservoir Segments that contributed to the well test outcome.
    /// </summary>
    [JsonPropertyName("CommingledReservoirEntityIDs")]
    public List<string> CommingledReservoirEntityIDs { get; set; }

    /// <summary>
    /// An array of StratigraphicUnitInterpretation, GeobodyInterpretation or RockFluidUnitInterpretation record Ids evaluated by the interpretation activity
    /// </summary>
    [JsonPropertyName("GeologicUnitInterpretationIDs")]
    public List<string> GeologicUnitInterpretationIDs { get; set; }

    /// <summary>
    /// The true vertical depth value for the reservoir pressure datum used in the analysis for calculation of the reservoir pressure. Note that this may vary from the reference depth record in the master-data Reservoir|ReservoirSegment as can change over the lifecycle of the Reservoir.
    /// </summary>
    [JsonPropertyName("ReservoirDatumTrueVerticalDepth")]
    public double? ReservoirDatumTrueVerticalDepth { get; set; }

    /// <summary>
    /// The subjective quality classification of the datum calculation. E.g. Excellent, Good, Poor etc. A Confidence classification could also be used here if there is an issue with the certainty of the interpretation.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-SubjectiveClassificationRating:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("ReservoirDatumCalculationSubjectiveClassificationRatingID")]
    public string ReservoirDatumCalculationSubjectiveClassificationRatingID { get; set; }

    /// <summary>
    /// An array of pressure correction(s) applied when interpreting pressure from the gauge depth to the reservoir pressure datum.
    /// </summary>
    [JsonPropertyName("AppliedPressureCorrections")]
    public List<WellPressureTestInterpretation_1_0_0DataInterpretationResultsAppliedPressureCorrections> AppliedPressureCorrections { get; set; }

    /// <summary>
    /// The interpreted reservoir pressure at the reservoir datum depth
    /// </summary>
    [JsonPropertyName("ReservoirPressureAtDatumDepth")]
    public double? ReservoirPressureAtDatumDepth { get; set; }

    /// <summary>
    /// Time stamped remarks associated with the reservoir properties calculation activity
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

}

/// <summary>
/// Segment that contains important reference elements used to support the interpretation activity
/// </summary>
public class WellPressureTestInterpretation_1_0_0DataInterpretationResultsInterpretationInput
{
    /// <summary>
    /// Optional reference to the WellboreMarkerSet containing the fluid contacts used for pressure test interpretation
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-WellboreMarkerSet:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("WellboreMarkerSetID")]
    public string WellboreMarkerSetID { get; set; }

    /// <summary>
    /// Optional reference to the GeoLabelSet containing information related to the Reservoir or ReservoirSegment
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:work-product-component\-\-GeoLabelSet:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("GeoLabelSetID")]
    public string GeoLabelSetID { get; set; }

    /// <summary>
    /// This contains the accepted fluid pressure gradients used in well test interpretation for the reservoir element. Fluid context is applied by the use of Facets e.g. what+Gas, what+Oil, qualifier+Total
    /// </summary>
    [JsonPropertyName("PressureGradients")]
    public List<WellPressureTestInterpretation_1_0_0DataInterpretationResultsInterpretationInputPressureGradients> PressureGradients { get; set; }

    /// <summary>
    /// Provides an array of general parameter values used in the Well Test Interpretation activity.
    /// </summary>
    [JsonPropertyName("Parameters")]
    public List<AbstractActivityParameter_1_1_0> Parameters { get; set; }

    /// <summary>
    /// Time stamped remarks associated with the input information used in the interpretation activity
    /// </summary>
    [JsonPropertyName("Remarks")]
    public List<AbstractRemark_1_0_0> Remarks { get; set; }

}

/// <summary>
/// This contains the accepted fluid pressure gradients used in well test interpretation for the reservoir element. Fluid context is applied by the use of Facets e.g. what+Gas, what+Oil, qualifier+Total
/// </summary>
public class WellPressureTestInterpretation_1_0_0DataInterpretationResultsInterpretationInputPressureGradients
{
    /// <summary>
    /// The gradient (change in pressure per unit length) value in the borehole, of the element defined by the FacetID, used for calculating the pressure in the perforated interval from pressure at sensor depth.
    /// </summary>
    [JsonPropertyName("PressureGradientValue")]
    public double? PressureGradientValue { get; set; }

    /// <summary>
    /// The pressure gradient that represents the depth vertically above that marks the limit of the high confidence range for the fluid marker.
    /// </summary>
    [JsonPropertyName("PressureGradientPositiveVerticalDeltaValue")]
    public double? PressureGradientPositiveVerticalDeltaValue { get; set; }

    /// <summary>
    /// The pressure gradient that represents the depth vertically below that marks the limit of the high confidence range for the fluid marker
    /// </summary>
    [JsonPropertyName("PressureGradientNegativeVerticalDeltaValue")]
    public double? PressureGradientNegativeVerticalDeltaValue { get; set; }

    /// <summary>
    /// The method that was used to calculate the Pressure Gradient Value including the uncertainty range
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-PressureGradientCalculationMethod:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("PressureGradientCalculationMethodID")]
    public string PressureGradientCalculationMethodID { get; set; }

    [JsonPropertyName("PropertyType")]
    public AbstractPropertyType_1_0_0? PropertyType { get; set; }

    /// <summary>
    /// Unique Nested Ordered Array with: FacetType, FacetRole, both calling specific references
    /// FacetType: Enumerations of the type of additional context about the nature of a property type (it may include conditions, direction, qualifiers, or statistics).
    /// FacetRole: Additional context about the nature of a property type. The purpose of such attribute is to minimize the need to create specialized property types by mutualizing some well known qualifiers such as "maximum", "minimum" which apply to a lot of different property types.
    /// </summary>
    [JsonPropertyName("FacetIDs")]
    public List<AbstractFacet_1_0_0> FacetIDs { get; set; }

    /// <summary>
    /// Unit of Measure used to capture Pressure Gradients - as not covered by Energistics Standard Units of Measure System
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("GradientsUOMID")]
    public string GradientsUOMID { get; set; }

}

/// <summary>
/// Pressure correction(s) applied when interpreting pressure from the gauge depth to the reservoir pressure datum. Further context can be applied to the Pressure Correction by the use of Facets e.g. what+Gas, what+Oil, qualifier+Total
/// </summary>
public class WellPressureTestInterpretation_1_0_0DataInterpretationResultsAppliedPressureCorrections
{
    /// <summary>
    /// The pressure correction value applied when interpreting pressure from the gauge depth to the reservoir pressure datum.
    /// </summary>
    [JsonPropertyName("PressureCorrectionValue")]
    public double? PressureCorrectionValue { get; set; }

    /// <summary>
    /// Unique Ordered Nested Array with: FacetType, FacetRole, both calling specific references
    /// FacetType: Enumerations of the type of additional context about the nature of a property type (it may include conditions, direction, qualifiers, or statistics).
    /// FacetRole: Additional context about the nature of a property type. The purpose of such attribute is to minimize the need to create specialized property types by mutualizing some well known qualifiers such as "maximum", "minimum" which apply to a lot of different property types.
    /// </summary>
    [JsonPropertyName("FacetIDs")]
    public List<AbstractFacet_1_0_0> FacetIDs { get; set; }

}
