// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Osdu.Client.Apis.File;

/// <summary>
/// A named list of entities in the data lake as a dictionary item.
/// </summary>
public class Ancestry
{
    /// <summary>
    /// An array of one or more entity references in the data lake.
    /// </summary>
    [JsonPropertyName("parents")]
    public List<string> Parents { get; set; }

}
