// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OsduCsharpClient.CrsCatalog.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OsduCsharpClient.CrsCatalog.V2.Search.Ct
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\search\ct
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CtRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CtRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/search/ct{?latitudeLower*,latitudeUpper*,limit*,longitudeLeft*,longitudeRight*,mode*,offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CtRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/search/ct{?latitudeLower*,latitudeUpper*,limit*,longitudeLeft*,longitudeRight*,mode*,offset*}", rawUrl)
        {
        }
        /// <summary>
        /// Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: &apos;&apos;name:&apos;&apos;,&apos;&apos;description:&apos;&apos;, &apos;&apos;type:&apos;&apos;, &apos;&apos;authority:&apos;&apos;, &apos;&apos;code:&apos;&apos;, &apos;&apos;deprecationState:&apos;&apos;, &apos;&apos;remarks:&apos;&apos;, &apos;&apos;lastModified:&apos;&apos;, &apos;&apos;source:&apos;&apos;, &apos;&apos;wellKnownText:&apos;&apos;, &apos;&apos;fromCRS.authority:&apos;&apos;, &apos;&apos;fromCRS.code:&apos;&apos;, &apos;&apos;toCRS.authority:&apos;&apos;, toCRS.code:&apos;&apos;, &apos;&apos;policy:&apos;&apos;. followed by a value. Example: &apos;&apos;fromCRS.code:4267&apos;&apos;.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.CrsCatalog.Models.CTResults"/></returns>
        /// <param name="body">Request to containing a Lucene style query string.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 404 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 409 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 500 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 502 status code</exception>
        /// <exception cref="global::OsduCsharpClient.CrsCatalog.Models.AppError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OsduCsharpClient.CrsCatalog.Models.CTResults?> PostAsync(global::OsduCsharpClient.CrsCatalog.Models.SearchRequest body, Action<RequestConfiguration<global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder.CtRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OsduCsharpClient.CrsCatalog.Models.CTResults> PostAsync(global::OsduCsharpClient.CrsCatalog.Models.SearchRequest body, Action<RequestConfiguration<global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder.CtRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "409", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "500", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "502", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
                { "503", global::OsduCsharpClient.CrsCatalog.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OsduCsharpClient.CrsCatalog.Models.CTResults>(requestInfo, global::OsduCsharpClient.CrsCatalog.Models.CTResults.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: &apos;&apos;name:&apos;&apos;,&apos;&apos;description:&apos;&apos;, &apos;&apos;type:&apos;&apos;, &apos;&apos;authority:&apos;&apos;, &apos;&apos;code:&apos;&apos;, &apos;&apos;deprecationState:&apos;&apos;, &apos;&apos;remarks:&apos;&apos;, &apos;&apos;lastModified:&apos;&apos;, &apos;&apos;source:&apos;&apos;, &apos;&apos;wellKnownText:&apos;&apos;, &apos;&apos;fromCRS.authority:&apos;&apos;, &apos;&apos;fromCRS.code:&apos;&apos;, &apos;&apos;toCRS.authority:&apos;&apos;, toCRS.code:&apos;&apos;, &apos;&apos;policy:&apos;&apos;. followed by a value. Example: &apos;&apos;fromCRS.code:4267&apos;&apos;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request to containing a Lucene style query string.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.CrsCatalog.Models.SearchRequest body, Action<RequestConfiguration<global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder.CtRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::OsduCsharpClient.CrsCatalog.Models.SearchRequest body, Action<RequestConfiguration<global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder.CtRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OsduCsharpClient.CrsCatalog.V2.Search.Ct.CtRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search cartographic transform records (any sub-type) by keywords and/or geographic area. Geographical constraints are passed (optionally) as parameters via the query URL, search keywords are passed via the request body. Query syntax follows Lucene style, default operator for multiple expressions is AND. The following keywords are supported: &apos;&apos;name:&apos;&apos;,&apos;&apos;description:&apos;&apos;, &apos;&apos;type:&apos;&apos;, &apos;&apos;authority:&apos;&apos;, &apos;&apos;code:&apos;&apos;, &apos;&apos;deprecationState:&apos;&apos;, &apos;&apos;remarks:&apos;&apos;, &apos;&apos;lastModified:&apos;&apos;, &apos;&apos;source:&apos;&apos;, &apos;&apos;wellKnownText:&apos;&apos;, &apos;&apos;fromCRS.authority:&apos;&apos;, &apos;&apos;fromCRS.code:&apos;&apos;, &apos;&apos;toCRS.authority:&apos;&apos;, toCRS.code:&apos;&apos;, &apos;&apos;policy:&apos;&apos;. followed by a value. Example: &apos;&apos;fromCRS.code:4267&apos;&apos;.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CtRequestBuilderPostQueryParameters 
        {
            [QueryParameter("latitudeLower")]
            public double? LatitudeLower { get; set; }
            [QueryParameter("latitudeUpper")]
            public double? LatitudeUpper { get; set; }
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            [QueryParameter("longitudeLeft")]
            public double? LongitudeLeft { get; set; }
            [QueryParameter("longitudeRight")]
            public double? LongitudeRight { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mode")]
            public string? Mode { get; set; }
#nullable restore
#else
            [QueryParameter("mode")]
            public string Mode { get; set; }
#endif
            [QueryParameter("offset")]
            public int? Offset { get; set; }
        }
    }
}
#pragma warning restore CS0618
