// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OsduCsharpClient.Unit.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Catalog : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lastModified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModified { get; set; }
#nullable restore
#else
        public string LastModified { get; set; }
#endif
        /// <summary>The mapStates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.MapState>? MapStates { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.MapState> MapStates { get; set; }
#endif
        /// <summary>The measurementMaps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.MeasurementMap>? MeasurementMaps { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.MeasurementMap> MeasurementMaps { get; set; }
#endif
        /// <summary>The measurements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.Measurement>? Measurements { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.Measurement> Measurements { get; set; }
#endif
        /// <summary>The totalMapStateCount property</summary>
        public int? TotalMapStateCount { get; set; }
        /// <summary>The totalMeasurementCount property</summary>
        public int? TotalMeasurementCount { get; set; }
        /// <summary>The totalMeasurementMapCount property</summary>
        public int? TotalMeasurementMapCount { get; set; }
        /// <summary>The totalUnitCount property</summary>
        public int? TotalUnitCount { get; set; }
        /// <summary>The totalUnitMapCount property</summary>
        public int? TotalUnitMapCount { get; set; }
        /// <summary>The totalUnitSystemCount property</summary>
        public int? TotalUnitSystemCount { get; set; }
        /// <summary>The unitMaps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.UnitMap>? UnitMaps { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.UnitMap> UnitMaps { get; set; }
#endif
        /// <summary>The units property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.Unit>? Units { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.Unit> Units { get; set; }
#endif
        /// <summary>The unitSystemInfos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OsduCsharpClient.Unit.Models.UnitSystemInfo>? UnitSystemInfos { get; set; }
#nullable restore
#else
        public List<global::OsduCsharpClient.Unit.Models.UnitSystemInfo> UnitSystemInfos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OsduCsharpClient.Unit.Models.Catalog"/> and sets the default values.
        /// </summary>
        public Catalog()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OsduCsharpClient.Unit.Models.Catalog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OsduCsharpClient.Unit.Models.Catalog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::OsduCsharpClient.Unit.Models.Catalog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lastModified", n => { LastModified = n.GetStringValue(); } },
                { "mapStates", n => { MapStates = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.MapState>(global::OsduCsharpClient.Unit.Models.MapState.CreateFromDiscriminatorValue)?.AsList(); } },
                { "measurementMaps", n => { MeasurementMaps = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.MeasurementMap>(global::OsduCsharpClient.Unit.Models.MeasurementMap.CreateFromDiscriminatorValue)?.AsList(); } },
                { "measurements", n => { Measurements = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.Measurement>(global::OsduCsharpClient.Unit.Models.Measurement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalMapStateCount", n => { TotalMapStateCount = n.GetIntValue(); } },
                { "totalMeasurementCount", n => { TotalMeasurementCount = n.GetIntValue(); } },
                { "totalMeasurementMapCount", n => { TotalMeasurementMapCount = n.GetIntValue(); } },
                { "totalUnitCount", n => { TotalUnitCount = n.GetIntValue(); } },
                { "totalUnitMapCount", n => { TotalUnitMapCount = n.GetIntValue(); } },
                { "totalUnitSystemCount", n => { TotalUnitSystemCount = n.GetIntValue(); } },
                { "unitMaps", n => { UnitMaps = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.UnitMap>(global::OsduCsharpClient.Unit.Models.UnitMap.CreateFromDiscriminatorValue)?.AsList(); } },
                { "unitSystemInfos", n => { UnitSystemInfos = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.UnitSystemInfo>(global::OsduCsharpClient.Unit.Models.UnitSystemInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "units", n => { Units = n.GetCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.Unit>(global::OsduCsharpClient.Unit.Models.Unit.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("lastModified", LastModified);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.MapState>("mapStates", MapStates);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.MeasurementMap>("measurementMaps", MeasurementMaps);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.Measurement>("measurements", Measurements);
            writer.WriteIntValue("totalMapStateCount", TotalMapStateCount);
            writer.WriteIntValue("totalMeasurementCount", TotalMeasurementCount);
            writer.WriteIntValue("totalMeasurementMapCount", TotalMeasurementMapCount);
            writer.WriteIntValue("totalUnitCount", TotalUnitCount);
            writer.WriteIntValue("totalUnitMapCount", TotalUnitMapCount);
            writer.WriteIntValue("totalUnitSystemCount", TotalUnitSystemCount);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.UnitMap>("unitMaps", UnitMaps);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.Unit>("units", Units);
            writer.WriteCollectionOfObjectValues<global::OsduCsharpClient.Unit.Models.UnitSystemInfo>("unitSystemInfos", UnitSystemInfos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
